"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the
map we want to create.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1000, 500)
# Dimension factor : 1.0
def add_boxes(playground):
    pass


def add_walls(playground):
    # vertical wall 0
    wall = NormalWall(pos_start=(-486, 237),
                      pos_end=(-486, -233))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 1
    wall = NormalWall(pos_start=(-480, 235),
                      pos_end=(483, 235))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 2
    wall = NormalWall(pos_start=(483, 237),
                      pos_end=(483, -233))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 3
    wall = NormalWall(pos_start=(-11, 134),
                      pos_end=(1, -236))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 4
    wall = NormalWall(pos_start=(3, -14),
                      pos_end=(315, -14))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 5
    wall = NormalWall(pos_start=(0, 134),
                      pos_end=(12, -233))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 6
    wall = NormalWall(pos_start=(12, -25),
                      pos_end=(315, -25))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 7
    wall = NormalWall(pos_start=(-487, -233),
                      pos_end=(485, -233))
    playground.add(wall, wall.wall_coordinates)

