"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the
map we want to create.
"""
import sys
from pathlib import Path

# Insert the parent directory of the current file's directory into sys.path.
# This allows Python to locate modules that are one level above the current
# script, in this case spg_overlay.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from spg_overlay.entities.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1700, 1100)
# Dimension factor : 1.0
def add_boxes(playground):
    # box 0
    box = NormalBox(up_left_point=(-367, -272),
                    width=171, height=50)
    playground.add(box, box.wall_coordinates)

    # box 1
    box = NormalBox(up_left_point=(-344, 86),
                    width=93, height=50)
    playground.add(box, box.wall_coordinates)


def add_walls(playground):
    # vertical wall 0
    wall = NormalWall(pos_start=(396, 541),
                      pos_end=(396, 332))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 1
    wall = NormalWall(pos_start=(394, 335),
                      pos_end=(702, 335))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 2
    wall = NormalWall(pos_start=(399, 542),
                      pos_end=(399, 334))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 3
    wall = NormalWall(pos_start=(-840, 539),
                      pos_end=(843, 539))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 4
    wall = NormalWall(pos_start=(-633, 521),
                      pos_end=(-633, 492))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 5
    wall = NormalWall(pos_start=(-632, 518),
                      pos_end=(-607, 518))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 6
    wall = NormalWall(pos_start=(-611, 520),
                      pos_end=(-611, 492))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 7
    wall = NormalWall(pos_start=(-564, 521),
                      pos_end=(-564, 492))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 8
    wall = NormalWall(pos_start=(-563, 518),
                      pos_end=(-538, 518))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 9
    wall = NormalWall(pos_start=(-542, 520),
                      pos_end=(-542, 492))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 10
    wall = NormalWall(pos_start=(-498, 521),
                      pos_end=(-498, 492))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 11
    wall = NormalWall(pos_start=(-497, 518),
                      pos_end=(-472, 518))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 12
    wall = NormalWall(pos_start=(-476, 520),
                      pos_end=(-476, 492))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 13
    wall = NormalWall(pos_start=(-433, 521),
                      pos_end=(-433, 492))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 14
    wall = NormalWall(pos_start=(-432, 518),
                      pos_end=(-407, 518))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 15
    wall = NormalWall(pos_start=(-411, 520),
                      pos_end=(-411, 492))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 16
    wall = NormalWall(pos_start=(-360, 521),
                      pos_end=(-360, 492))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 17
    wall = NormalWall(pos_start=(-359, 518),
                      pos_end=(-334, 518))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 18
    wall = NormalWall(pos_start=(-338, 520),
                      pos_end=(-338, 492))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 19
    wall = NormalWall(pos_start=(-279, 521),
                      pos_end=(-279, 492))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 20
    wall = NormalWall(pos_start=(-278, 518),
                      pos_end=(-253, 518))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 21
    wall = NormalWall(pos_start=(-257, 520),
                      pos_end=(-257, 492))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 22
    wall = NormalWall(pos_start=(-635, 496),
                      pos_end=(-608, 496))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 23
    wall = NormalWall(pos_start=(-566, 496),
                      pos_end=(-539, 496))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 24
    wall = NormalWall(pos_start=(-500, 496),
                      pos_end=(-473, 496))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 25
    wall = NormalWall(pos_start=(-435, 496),
                      pos_end=(-408, 496))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 26
    wall = NormalWall(pos_start=(-362, 496),
                      pos_end=(-335, 496))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 27
    wall = NormalWall(pos_start=(-281, 496),
                      pos_end=(-254, 496))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 28
    wall = NormalWall(pos_start=(630, 454),
                      pos_end=(630, 334))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 29
    wall = NormalWall(pos_start=(633, 453),
                      pos_end=(633, 334))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 30
    wall = NormalWall(pos_start=(310, 378),
                      pos_end=(310, 349))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 31
    wall = NormalWall(pos_start=(311, 375),
                      pos_end=(336, 375))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 32
    wall = NormalWall(pos_start=(332, 377),
                      pos_end=(332, 349))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 33
    wall = NormalWall(pos_start=(-843, 262),
                      pos_end=(-667, 262))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 34
    wall = NormalWall(pos_start=(-670, 353),
                      pos_end=(-89, 353))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 35
    wall = NormalWall(pos_start=(-93, 355),
                      pos_end=(-93, 69))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 36
    wall = NormalWall(pos_start=(308, 353),
                      pos_end=(335, 353))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 37
    wall = NormalWall(pos_start=(-665, 354),
                      pos_end=(-665, 80))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 38
    wall = NormalWall(pos_start=(-495, 354),
                      pos_end=(-495, 181))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 39
    wall = NormalWall(pos_start=(-310, 354),
                      pos_end=(-310, 306))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 40
    wall = NormalWall(pos_start=(-668, 350),
                      pos_end=(-92, 350))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 41
    wall = NormalWall(pos_start=(-498, 353),
                      pos_end=(-498, 174))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 42
    wall = NormalWall(pos_start=(-313, 353),
                      pos_end=(-313, 306))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 43
    wall = NormalWall(pos_start=(-96, 353),
                      pos_end=(-96, 80))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 44
    wall = NormalWall(pos_start=(396, 338),
                      pos_end=(702, 338))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 45
    wall = NormalWall(pos_start=(784, 338),
                      pos_end=(842, 338))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 46
    wall = NormalWall(pos_start=(784, 335),
                      pos_end=(843, 335))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 47
    wall = NormalWall(pos_start=(839, 541),
                      pos_end=(839, -541))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 48
    wall = NormalWall(pos_start=(614, 321),
                      pos_end=(614, 292))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 49
    wall = NormalWall(pos_start=(615, 318),
                      pos_end=(640, 318))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 50
    wall = NormalWall(pos_start=(636, 320),
                      pos_end=(636, 292))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 51
    wall = NormalWall(pos_start=(612, 296),
                      pos_end=(639, 296))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 52
    wall = NormalWall(pos_start=(-843, 259),
                      pos_end=(-664, 259))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 53
    wall = NormalWall(pos_start=(-668, 357),
                      pos_end=(-668, 80))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 54
    wall = NormalWall(pos_start=(207, 243),
                      pos_end=(207, 214))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 55
    wall = NormalWall(pos_start=(208, 240),
                      pos_end=(233, 240))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 56
    wall = NormalWall(pos_start=(229, 242),
                      pos_end=(229, 214))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 57
    wall = NormalWall(pos_start=(486, 225),
                      pos_end=(486, 196))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 58
    wall = NormalWall(pos_start=(487, 222),
                      pos_end=(512, 222))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 59
    wall = NormalWall(pos_start=(508, 224),
                      pos_end=(508, 196))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 60
    wall = NormalWall(pos_start=(-313, 225),
                      pos_end=(-313, 181))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 61
    wall = NormalWall(pos_start=(-310, 224),
                      pos_end=(-310, 178))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 62
    wall = NormalWall(pos_start=(-410, 182),
                      pos_end=(-308, 182))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 63
    wall = NormalWall(pos_start=(205, 218),
                      pos_end=(232, 218))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 64
    wall = NormalWall(pos_start=(484, 200),
                      pos_end=(511, 200))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 65
    wall = NormalWall(pos_start=(-498, 185),
                      pos_end=(-310, 185))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 66
    wall = NormalWall(pos_start=(28, 187),
                      pos_end=(28, 158))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 67
    wall = NormalWall(pos_start=(29, 184),
                      pos_end=(54, 184))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 68
    wall = NormalWall(pos_start=(50, 186),
                      pos_end=(50, 158))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 69
    wall = NormalWall(pos_start=(-498, 182),
                      pos_end=(-405, 182))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 70
    wall = NormalWall(pos_start=(26, 162),
                      pos_end=(53, 162))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 71
    wall = NormalWall(pos_start=(-413, 81),
                      pos_end=(-338, 81))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 72
    wall = NormalWall(pos_start=(-342, 83),
                      pos_end=(-342, 39))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 73
    wall = NormalWall(pos_start=(-344, 42),
                      pos_end=(-253, 42))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 74
    wall = NormalWall(pos_start=(-669, 81),
                      pos_end=(-491, 81))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 75
    wall = NormalWall(pos_start=(-769, 84),
                      pos_end=(-495, 84))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 76
    wall = NormalWall(pos_start=(-409, 84),
                      pos_end=(-93, 84))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 77
    wall = NormalWall(pos_start=(-769, 81),
                      pos_end=(-664, 81))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 78
    wall = NormalWall(pos_start=(-257, 85),
                      pos_end=(-257, 39))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 79
    wall = NormalWall(pos_start=(-259, 81),
                      pos_end=(-92, 81))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 80
    wall = NormalWall(pos_start=(328, 18),
                      pos_end=(328, -11))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 81
    wall = NormalWall(pos_start=(329, 15),
                      pos_end=(354, 15))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 82
    wall = NormalWall(pos_start=(350, 17),
                      pos_end=(350, -11))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 83
    wall = NormalWall(pos_start=(326, -7),
                      pos_end=(353, -7))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 84
    wall = NormalWall(pos_start=(-668, -8),
                      pos_end=(-668, -318))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 85
    wall = NormalWall(pos_start=(-668, -18),
                      pos_end=(-465, -18))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 86
    wall = NormalWall(pos_start=(-469, -16),
                      pos_end=(-469, -232))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 87
    wall = NormalWall(pos_start=(-765, -46),
                      pos_end=(-765, -243))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 88
    wall = NormalWall(pos_start=(-665, -47),
                      pos_end=(-665, -318))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 89
    wall = NormalWall(pos_start=(-665, -50),
                      pos_end=(-497, -50))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 90
    wall = NormalWall(pos_start=(-501, -48),
                      pos_end=(-501, -231))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 91
    wall = NormalWall(pos_start=(-503, -228),
                      pos_end=(-466, -228))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 92
    wall = NormalWall(pos_start=(-762, -47),
                      pos_end=(-762, -243))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 93
    wall = NormalWall(pos_start=(51, -54),
                      pos_end=(51, -83))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 94
    wall = NormalWall(pos_start=(52, -57),
                      pos_end=(77, -57))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 95
    wall = NormalWall(pos_start=(73, -55),
                      pos_end=(73, -83))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 96
    wall = NormalWall(pos_start=(49, -79),
                      pos_end=(76, -79))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 97
    wall = NormalWall(pos_start=(593, -158),
                      pos_end=(593, -187))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 98
    wall = NormalWall(pos_start=(594, -161),
                      pos_end=(619, -161))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 99
    wall = NormalWall(pos_start=(615, -159),
                      pos_end=(615, -187))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 100
    wall = NormalWall(pos_start=(208, -171),
                      pos_end=(208, -200))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 101
    wall = NormalWall(pos_start=(209, -174),
                      pos_end=(234, -174))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 102
    wall = NormalWall(pos_start=(230, -172),
                      pos_end=(230, -200))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 103
    wall = NormalWall(pos_start=(591, -183),
                      pos_end=(618, -183))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 104
    wall = NormalWall(pos_start=(206, -196),
                      pos_end=(233, -196))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 105
    wall = NormalWall(pos_start=(447, -255),
                      pos_end=(447, -284))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 106
    wall = NormalWall(pos_start=(448, -258),
                      pos_end=(473, -258))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 107
    wall = NormalWall(pos_start=(469, -256),
                      pos_end=(469, -284))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 108
    wall = NormalWall(pos_start=(-365, -271),
                      pos_end=(-365, -318))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 109
    wall = NormalWall(pos_start=(-364, -274),
                      pos_end=(-198, -274))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 110
    wall = NormalWall(pos_start=(-202, -272),
                      pos_end=(-202, -317))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 111
    wall = NormalWall(pos_start=(445, -280),
                      pos_end=(472, -280))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 112
    wall = NormalWall(pos_start=(-843, -314),
                      pos_end=(-364, -314))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 113
    wall = NormalWall(pos_start=(-204, -314),
                      pos_end=(629, -314))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 114
    wall = NormalWall(pos_start=(-546, -317),
                      pos_end=(-359, -317))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 115
    wall = NormalWall(pos_start=(-542, -316),
                      pos_end=(-542, -338))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 116
    wall = NormalWall(pos_start=(-96, -12),
                      pos_end=(-96, -348))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 117
    wall = NormalWall(pos_start=(-841, 542),
                      pos_end=(-841, -542))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 118
    wall = NormalWall(pos_start=(-843, -317),
                      pos_end=(-541, -317))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 119
    wall = NormalWall(pos_start=(-93, -13),
                      pos_end=(-93, -347))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 120
    wall = NormalWall(pos_start=(-366, -317),
                      pos_end=(628, -317))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 121
    wall = NormalWall(pos_start=(-545, -314),
                      pos_end=(-545, -337))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 122
    wall = NormalWall(pos_start=(-545, -419),
                      pos_end=(-545, -542))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 123
    wall = NormalWall(pos_start=(-542, -420),
                      pos_end=(-542, -542))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 124
    wall = NormalWall(pos_start=(-96, -512),
                      pos_end=(-96, -542))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 125
    wall = NormalWall(pos_start=(-93, -513),
                      pos_end=(-93, -542))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 126
    wall = NormalWall(pos_start=(-843, -538),
                      pos_end=(842, -538))
    playground.add(wall, wall.wall_coordinates)

