"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the map we want to create.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1819, 1350)
# Dimension factor : 1.0
def add_boxes(playground):
    # box 0
    box = NormalBox(up_left_point=(-894, -508),
                    width=123, height=88)
    playground.add(box, box.wall_coordinates)

    # box 1
    box = NormalBox(up_left_point=(-694, -496),
                    width=80, height=164)
    playground.add(box, box.wall_coordinates)

    # box 2
    box = NormalBox(up_left_point=(-412, 305),
                    width=264, height=317)
    playground.add(box, box.wall_coordinates)

    # box 3
    box = NormalBox(up_left_point=(-384, 534),
                    width=118, height=120)
    playground.add(box, box.wall_coordinates)

    # box 4
    box = NormalBox(up_left_point=(618, 618),
                    width=89, height=148)
    playground.add(box, box.wall_coordinates)

    # box 5
    box = NormalBox(up_left_point=(72, 663),
                    width=89, height=157)
    playground.add(box, box.wall_coordinates)

    # box 6
    box = NormalBox(up_left_point=(-90, 663),
                    width=88, height=157)
    playground.add(box, box.wall_coordinates)

    # boxes cadre
    box = NormalBox(up_left_point=(-910, 675),
                    width=20, height=1350)
    playground.add(box, box.wall_coordinates)

    box = NormalBox(up_left_point=(-910, 675),
                    width=1820, height=16)
    playground.add(box, box.wall_coordinates)

    box = NormalBox(up_left_point=(-910, -655),
                    width=1820, height=20)
    playground.add(box, box.wall_coordinates)

    box = NormalBox(up_left_point=(887, 675),
                    width=23, height=1350)
    playground.add(box, box.wall_coordinates)


def add_walls(playground):
    # vertical wall 0
    wall = NormalWall(pos_start=(-891, 663),
                      pos_end=(-891, -656))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 1
    wall = NormalWall(pos_start=(-892, 661),
                      pos_end=(888, 661))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 2
    wall = NormalWall(pos_start=(-510, 661),
                      pos_end=(-510, 415))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 3
    wall = NormalWall(pos_start=(-152, 661),
                      pos_end=(-152, 612))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 4
    wall = NormalWall(pos_start=(-890, 659),
                      pos_end=(-86, 659))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 5
    wall = NormalWall(pos_start=(-8, 661),
                      pos_end=(-8, 510))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 6
    wall = NormalWall(pos_start=(-90, 512),
                      pos_end=(-8, 512))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 7
    wall = NormalWall(pos_start=(-8, 659),
                      pos_end=(76, 659))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 8
    wall = NormalWall(pos_start=(156, 661),
                      pos_end=(156, 510))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 9
    wall = NormalWall(pos_start=(74, 512),
                      pos_end=(156, 512))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 10
    wall = NormalWall(pos_start=(360, 661),
                      pos_end=(360, 325))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 11
    wall = NormalWall(pos_start=(156, 659),
                      pos_end=(886, 659))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 12
    wall = NormalWall(pos_start=(886, 661),
                      pos_end=(886, -655))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 13
    wall = NormalWall(pos_start=(-512, 660),
                      pos_end=(-512, 415))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 14
    wall = NormalWall(pos_start=(-154, 660),
                      pos_end=(-154, 612))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 15
    wall = NormalWall(pos_start=(-88, 660),
                      pos_end=(-88, 511))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 16
    wall = NormalWall(pos_start=(74, 660),
                      pos_end=(74, 511))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 17
    wall = NormalWall(pos_start=(358, 660),
                      pos_end=(358, 325))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 18
    wall = NormalWall(pos_start=(884, 660),
                      pos_end=(884, -655))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 19
    wall = NormalWall(pos_start=(621, 617),
                      pos_end=(621, 474))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 20
    wall = NormalWall(pos_start=(622, 616),
                      pos_end=(704, 616))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 21
    wall = NormalWall(pos_start=(702, 616),
                      pos_end=(702, 474))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 22
    wall = NormalWall(pos_start=(-890, 537),
                      pos_end=(-750, 537))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 23
    wall = NormalWall(pos_start=(-890, 535),
                      pos_end=(-752, 535))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 24
    wall = NormalWall(pos_start=(-382, 533),
                      pos_end=(-382, 418))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 25
    wall = NormalWall(pos_start=(-382, 532),
                      pos_end=(-270, 532))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 26
    wall = NormalWall(pos_start=(-272, 532),
                      pos_end=(-272, 418))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 27
    wall = NormalWall(pos_start=(-154, 516),
                      pos_end=(-154, 301))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 28
    wall = NormalWall(pos_start=(620, 476),
                      pos_end=(702, 476))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 29
    wall = NormalWall(pos_start=(-382, 420),
                      pos_end=(-272, 420))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 30
    wall = NormalWall(pos_start=(-702, 417),
                      pos_end=(-512, 417))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 31
    wall = NormalWall(pos_start=(-702, 415),
                      pos_end=(-510, 415))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 32
    wall = NormalWall(pos_start=(-890, 303),
                      pos_end=(-502, 303))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 33
    wall = NormalWall(pos_start=(-409, 304),
                      pos_end=(-409, -8))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 34
    wall = NormalWall(pos_start=(-408, 303),
                      pos_end=(-154, 303))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 35
    wall = NormalWall(pos_start=(-726, 303),
                      pos_end=(-726, 289))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 36
    wall = NormalWall(pos_start=(-890, 301),
                      pos_end=(-504, 301))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 37
    wall = NormalWall(pos_start=(-504, 303),
                      pos_end=(-504, -489))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 38
    wall = NormalWall(pos_start=(-153, 517),
                      pos_end=(-153, -7))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 39
    wall = NormalWall(pos_start=(-154, -5),
                      pos_end=(630, -5))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 40
    wall = NormalWall(pos_start=(-506, 302),
                      pos_end=(-506, -489))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 41
    wall = NormalWall(pos_start=(-726, 172),
                      pos_end=(-726, 21))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 42
    wall = NormalWall(pos_start=(-728, 171),
                      pos_end=(-728, 21))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 43
    wall = NormalWall(pos_start=(-890, 59),
                      pos_end=(-858, 59))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 44
    wall = NormalWall(pos_start=(-750, 59),
                      pos_end=(-634, 59))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 45
    wall = NormalWall(pos_start=(-524, 59),
                      pos_end=(-504, 59))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 46
    wall = NormalWall(pos_start=(-890, 57),
                      pos_end=(-858, 57))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 47
    wall = NormalWall(pos_start=(-752, 57),
                      pos_end=(-636, 57))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 48
    wall = NormalWall(pos_start=(-526, 57),
                      pos_end=(-504, 57))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 49
    wall = NormalWall(pos_start=(722, -5),
                      pos_end=(886, -5))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 50
    wall = NormalWall(pos_start=(-410, -7),
                      pos_end=(620, -7))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 51
    wall = NormalWall(pos_start=(730, -5),
                      pos_end=(730, -220))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 52
    wall = NormalWall(pos_start=(730, -7),
                      pos_end=(886, -7))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 53
    wall = NormalWall(pos_start=(728, -6),
                      pos_end=(728, -220))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 54
    wall = NormalWall(pos_start=(-726, -71),
                      pos_end=(-726, -194))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 55
    wall = NormalWall(pos_start=(-728, -72),
                      pos_end=(-728, -194))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 56
    wall = NormalWall(pos_start=(-412, -95),
                      pos_end=(-412, -655))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 57
    wall = NormalWall(pos_start=(-412, -97),
                      pos_end=(-292, -97))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 58
    wall = NormalWall(pos_start=(-412, -99),
                      pos_end=(-292, -99))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 59
    wall = NormalWall(pos_start=(-194, -99),
                      pos_end=(618, -99))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 60
    wall = NormalWall(pos_start=(-154, -98),
                      pos_end=(-154, -655))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 61
    wall = NormalWall(pos_start=(170, -99),
                      pos_end=(170, -122))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 62
    wall = NormalWall(pos_start=(-196, -101),
                      pos_end=(620, -101))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 63
    wall = NormalWall(pos_start=(168, -100),
                      pos_end=(168, -122))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 64
    wall = NormalWall(pos_start=(-890, -192),
                      pos_end=(-858, -192))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 65
    wall = NormalWall(pos_start=(-754, -192),
                      pos_end=(-627, -192))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 66
    wall = NormalWall(pos_start=(-526, -192),
                      pos_end=(-504, -192))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 67
    wall = NormalWall(pos_start=(-890, 661),
                      pos_end=(-890, -512))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 68
    wall = NormalWall(pos_start=(-890, -194),
                      pos_end=(-860, -194))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 69
    wall = NormalWall(pos_start=(-670, -192),
                      pos_end=(-670, -408))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 70
    wall = NormalWall(pos_start=(-756, -194),
                      pos_end=(-628, -194))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 71
    wall = NormalWall(pos_start=(-526, -194),
                      pos_end=(-504, -194))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 72
    wall = NormalWall(pos_start=(-672, -193),
                      pos_end=(-672, -409))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 73
    wall = NormalWall(pos_start=(-314, -219),
                      pos_end=(-152, -219))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 74
    wall = NormalWall(pos_start=(-314, -221),
                      pos_end=(-152, -221))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 75
    wall = NormalWall(pos_start=(168, -226),
                      pos_end=(168, -655))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 76
    wall = NormalWall(pos_start=(730, -315),
                      pos_end=(730, -336))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 77
    wall = NormalWall(pos_start=(728, -316),
                      pos_end=(728, -336))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 78
    wall = NormalWall(pos_start=(-412, -332),
                      pos_end=(-254, -332))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 79
    wall = NormalWall(pos_start=(-152, -332),
                      pos_end=(-106, -332))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 80
    wall = NormalWall(pos_start=(-10, -332),
                      pos_end=(215, -332))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 81
    wall = NormalWall(pos_start=(-410, -97),
                      pos_end=(-410, -655))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 82
    wall = NormalWall(pos_start=(-338, -332),
                      pos_end=(-338, -554))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 83
    wall = NormalWall(pos_start=(-412, -334),
                      pos_end=(-254, -334))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 84
    wall = NormalWall(pos_start=(-152, -99),
                      pos_end=(-152, -655))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 85
    wall = NormalWall(pos_start=(-152, -334),
                      pos_end=(-106, -334))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 86
    wall = NormalWall(pos_start=(328, -334),
                      pos_end=(759, -334))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 87
    wall = NormalWall(pos_start=(852, -334),
                      pos_end=(886, -334))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 88
    wall = NormalWall(pos_start=(-340, -333),
                      pos_end=(-340, -554))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 89
    wall = NormalWall(pos_start=(169, -225),
                      pos_end=(169, -655))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 90
    wall = NormalWall(pos_start=(-10, -334),
                      pos_end=(214, -334))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 91
    wall = NormalWall(pos_start=(464, -334),
                      pos_end=(464, -518))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 92
    wall = NormalWall(pos_start=(326, -336),
                      pos_end=(758, -336))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 93
    wall = NormalWall(pos_start=(850, -336),
                      pos_end=(886, -336))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 94
    wall = NormalWall(pos_start=(462, -335),
                      pos_end=(462, -518))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 95
    wall = NormalWall(pos_start=(-670, -406),
                      pos_end=(-504, -406))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 96
    wall = NormalWall(pos_start=(-672, -408),
                      pos_end=(-504, -408))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 97
    wall = NormalWall(pos_start=(-252, -435),
                      pos_end=(-252, -655))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 98
    wall = NormalWall(pos_start=(-254, -436),
                      pos_end=(-254, -655))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 99
    wall = NormalWall(pos_start=(-691, -497),
                      pos_end=(-691, -655))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 100
    wall = NormalWall(pos_start=(-892, -653),
                      pos_end=(-692, -653))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 101
    wall = NormalWall(pos_start=(-690, -498),
                      pos_end=(-617, -498))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 102
    wall = NormalWall(pos_start=(-620, -498),
                      pos_end=(-620, -654))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 103
    wall = NormalWall(pos_start=(-890, -510),
                      pos_end=(-774, -510))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 104
    wall = NormalWall(pos_start=(-776, -510),
                      pos_end=(-776, -592))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 105
    wall = NormalWall(pos_start=(-889, -588),
                      pos_end=(-889, -654))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 106
    wall = NormalWall(pos_start=(-890, -590),
                      pos_end=(-776, -590))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 107
    wall = NormalWall(pos_start=(465, -620),
                      pos_end=(465, -655))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 108
    wall = NormalWall(pos_start=(462, -621),
                      pos_end=(462, -655))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 109
    wall = NormalWall(pos_start=(-620, -653),
                      pos_end=(886, -653))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 110
    wall = NormalWall(pos_start=(-892, -655),
                      pos_end=(886, -655))
    playground.add(wall, wall.wall_coordinates)
