"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the map we want to create.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1110,750)
# Dimension factor : 0.6684491978609626
def add_boxes(playground):
    # box 0
    box = NormalBox(up_left_point=(99.0, -15.0),
                    width=109, height=176)
    playground.add(box, box.wall_coordinates)

    # box 1
    box = NormalBox(up_left_point=(99.0, 349.0),
                    width=110, height=182)
    playground.add(box, box.wall_coordinates)

    # box 2
    box = NormalBox(up_left_point=(-41.0, 350.0),
                    width=105, height=182)
    playground.add(box, box.wall_coordinates)


def add_walls(playground):
    # vertical wall 0
    wall = NormalWall(pos_start=(-549.0, 369.0),
                      pos_end=(-549.0, -200.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 1
    wall = NormalWall(pos_start=(-356.0, 368.0),
                      pos_end=(-356.0, 226.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 2
    wall = NormalWall(pos_start=(-84.0, 370.0),
                      pos_end=(-84.0, 222.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 3
    wall = NormalWall(pos_start=(549.0, 368.0),
                      pos_end=(549.0, -370.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 4
    wall = NormalWall(pos_start=(-549.0, 367.0),
                      pos_end=(551.0, 367.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 5
    wall = NormalWall(pos_start=(-86.0, 368.0),
                      pos_end=(-86.0, 223.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 6
    wall = NormalWall(pos_start=(-40.0, 350.0),
                      pos_end=(-40.0, 170.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 7
    wall = NormalWall(pos_start=(-40.0, 349.0),
                      pos_end=(62.0, 349.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 8
    wall = NormalWall(pos_start=(60.0, 350.0),
                      pos_end=(60.0, 170.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 9
    wall = NormalWall(pos_start=(101.0, 349.0),
                      pos_end=(101.0, 168.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 10
    wall = NormalWall(pos_start=(101.0, 348.0),
                      pos_end=(208.0, 348.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 11
    wall = NormalWall(pos_start=(206.0, 348.0),
                      pos_end=(206.0, 168.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 12
    wall = NormalWall(pos_start=(-416.0, 307.0),
                      pos_end=(-416.0, 283.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 13
    wall = NormalWall(pos_start=(-417.0, 307.0),
                      pos_end=(-417.0, 283.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 14
    wall = NormalWall(pos_start=(-550.0, 295.0),
                      pos_end=(-416.0, 295.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 15
    wall = NormalWall(pos_start=(-550.0, 293.0),
                      pos_end=(-416.0, 293.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 16
    wall = NormalWall(pos_start=(-356.0, 237.0),
                      pos_end=(-155.0, 237.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 17
    wall = NormalWall(pos_start=(-354.0, 369.0),
                      pos_end=(-354.0, 227.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 18
    wall = NormalWall(pos_start=(-260.0, 238.0),
                      pos_end=(-260.0, 219.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 19
    wall = NormalWall(pos_start=(-166.0, 238.0),
                      pos_end=(-166.0, -33.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 20
    wall = NormalWall(pos_start=(-356.0, 236.0),
                      pos_end=(-155.0, 236.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 21
    wall = NormalWall(pos_start=(-261.0, 237.0),
                      pos_end=(-261.0, 219.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 22
    wall = NormalWall(pos_start=(-167.0, 237.0),
                      pos_end=(-167.0, -33.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 23
    wall = NormalWall(pos_start=(-416.0, 237.0),
                      pos_end=(-416.0, 215.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 24
    wall = NormalWall(pos_start=(-417.0, 236.0),
                      pos_end=(-417.0, 215.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 25
    wall = NormalWall(pos_start=(-550.0, 227.0),
                      pos_end=(-416.0, 227.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 26
    wall = NormalWall(pos_start=(-550.0, 225.0),
                      pos_end=(-416.0, 225.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 27
    wall = NormalWall(pos_start=(-416.0, 177.0),
                      pos_end=(-416.0, 158.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 28
    wall = NormalWall(pos_start=(-417.0, 176.0),
                      pos_end=(-417.0, 158.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 29
    wall = NormalWall(pos_start=(-40.0, 172.0),
                      pos_end=(61.0, 172.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 30
    wall = NormalWall(pos_start=(100.0, 170.0),
                      pos_end=(207.0, 170.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 31
    wall = NormalWall(pos_start=(-550.0, 169.0),
                      pos_end=(-416.0, 169.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 32
    wall = NormalWall(pos_start=(-550.0, 168.0),
                      pos_end=(-416.0, 168.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 33
    wall = NormalWall(pos_start=(-84.0, 170.0),
                      pos_end=(-84.0, -98.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 34
    wall = NormalWall(pos_start=(-86.0, 169.0),
                      pos_end=(-86.0, -98.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 35
    wall = NormalWall(pos_start=(-260.0, 161.0),
                      pos_end=(-260.0, 42.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 36
    wall = NormalWall(pos_start=(-261.0, 160.0),
                      pos_end=(-261.0, 42.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 37
    wall = NormalWall(pos_start=(-355.0, 144.0),
                      pos_end=(-332.0, 144.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 38
    wall = NormalWall(pos_start=(-356.0, 156.0),
                      pos_end=(-356.0, -33.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 39
    wall = NormalWall(pos_start=(-273.0, 144.0),
                      pos_end=(-239.0, 144.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 40
    wall = NormalWall(pos_start=(-183.0, 144.0),
                      pos_end=(-166.0, 144.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 41
    wall = NormalWall(pos_start=(-356.0, 143.0),
                      pos_end=(-333.0, 143.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 42
    wall = NormalWall(pos_start=(-274.0, 143.0),
                      pos_end=(-239.0, 143.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 43
    wall = NormalWall(pos_start=(-183.0, 143.0),
                      pos_end=(-166.0, 143.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 44
    wall = NormalWall(pos_start=(398.0, 142.0),
                      pos_end=(398.0, 128.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 45
    wall = NormalWall(pos_start=(398.0, 141.0),
                      pos_end=(412.0, 141.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 46
    wall = NormalWall(pos_start=(410.0, 142.0),
                      pos_end=(410.0, 128.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 47
    wall = NormalWall(pos_start=(75.0, 135.0),
                      pos_end=(75.0, 120.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 48
    wall = NormalWall(pos_start=(75.0, 134.0),
                      pos_end=(89.0, 134.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 49
    wall = NormalWall(pos_start=(87.0, 134.0),
                      pos_end=(87.0, 120.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 50
    wall = NormalWall(pos_start=(398.0, 130.0),
                      pos_end=(411.0, 130.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 51
    wall = NormalWall(pos_start=(75.0, 122.0),
                      pos_end=(88.0, 122.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 52
    wall = NormalWall(pos_start=(-416.0, 122.0),
                      pos_end=(-416.0, 37.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 53
    wall = NormalWall(pos_start=(-417.0, 121.0),
                      pos_end=(-417.0, 37.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 54
    wall = NormalWall(pos_start=(-356.0, 54.0),
                      pos_end=(-239.0, 54.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 55
    wall = NormalWall(pos_start=(-183.0, 54.0),
                      pos_end=(-166.0, 54.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 56
    wall = NormalWall(pos_start=(-356.0, 53.0),
                      pos_end=(-239.0, 53.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 57
    wall = NormalWall(pos_start=(-183.0, 53.0),
                      pos_end=(-166.0, 53.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 58
    wall = NormalWall(pos_start=(-550.0, 50.0),
                      pos_end=(-416.0, 50.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 59
    wall = NormalWall(pos_start=(-550.0, 49.0),
                      pos_end=(-416.0, 49.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 60
    wall = NormalWall(pos_start=(77.0, 17.0),
                      pos_end=(77.0, 2.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 61
    wall = NormalWall(pos_start=(77.0, 15.0),
                      pos_end=(91.0, 15.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 62
    wall = NormalWall(pos_start=(89.0, 16.0),
                      pos_end=(89.0, 2.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 63
    wall = NormalWall(pos_start=(402.0, 9.0),
                      pos_end=(402.0, -6.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 64
    wall = NormalWall(pos_start=(402.0, 7.0),
                      pos_end=(416.0, 7.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 65
    wall = NormalWall(pos_start=(414.0, 8.0),
                      pos_end=(414.0, -6.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 66
    wall = NormalWall(pos_start=(77.0, 4.0),
                      pos_end=(90.0, 4.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 67
    wall = NormalWall(pos_start=(402.0, -4.0),
                      pos_end=(415.0, -4.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 68
    wall = NormalWall(pos_start=(-416.0, -3.0),
                      pos_end=(-416.0, -35.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 69
    wall = NormalWall(pos_start=(-417.0, -3.0),
                      pos_end=(-417.0, -35.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 70
    wall = NormalWall(pos_start=(-550.0, -10.0),
                      pos_end=(-416.0, -10.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 71
    wall = NormalWall(pos_start=(-550.0, -11.0),
                      pos_end=(-416.0, -11.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 72
    wall = NormalWall(pos_start=(101.0, -15.0),
                      pos_end=(101.0, -188.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 73
    wall = NormalWall(pos_start=(101.0, -16.0),
                      pos_end=(206.0, -16.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 74
    wall = NormalWall(pos_start=(204.0, -15.0),
                      pos_end=(204.0, -188.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 75
    wall = NormalWall(pos_start=(-356.0, -19.0),
                      pos_end=(-239.0, -19.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 76
    wall = NormalWall(pos_start=(-183.0, -19.0),
                      pos_end=(-166.0, -19.0))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 77
    wall = NormalWall(pos_start=(-357.0, 156.0),
                      pos_end=(-352.0, -33.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 78
    wall = NormalWall(pos_start=(-356.0, -21.0),
                      pos_end=(-239.0, -21.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 79
    wall = NormalWall(pos_start=(-183.0, -21.0),
                      pos_end=(-166.0, -21.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 80
    wall = NormalWall(pos_start=(-416.0, -86.0),
                      pos_end=(-416.0, -202.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 81
    wall = NormalWall(pos_start=(-417.0, -86.0),
                      pos_end=(-417.0, -202.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 82
    wall = NormalWall(pos_start=(-166.0, -88.0),
                      pos_end=(-166.0, -102.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 83
    wall = NormalWall(pos_start=(-167.0, -89.0),
                      pos_end=(-167.0, -102.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 84
    wall = NormalWall(pos_start=(-350.0, -100.0),
                      pos_end=(-89.0, -100.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 85
    wall = NormalWall(pos_start=(-301.0, -99.0),
                      pos_end=(-301.0, -126.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 86
    wall = NormalWall(pos_start=(-131.0, -99.0),
                      pos_end=(-131.0, -201.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 87
    wall = NormalWall(pos_start=(-351.0, -101.0),
                      pos_end=(-90.0, -101.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 88
    wall = NormalWall(pos_start=(-302.0, -100.0),
                      pos_end=(-302.0, -126.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 89
    wall = NormalWall(pos_start=(-133.0, -100.0),
                      pos_end=(-133.0, -201.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 90
    wall = NormalWall(pos_start=(-550.0, -106.0),
                      pos_end=(-514.0, -106.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 91
    wall = NormalWall(pos_start=(-446.0, -106.0),
                      pos_end=(-416.0, -106.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 92
    wall = NormalWall(pos_start=(-550.0, -108.0),
                      pos_end=(-515.0, -108.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 93
    wall = NormalWall(pos_start=(-447.0, -108.0),
                      pos_end=(-416.0, -108.0))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 94
    wall = NormalWall(pos_start=(-304.0, -178.0),
                      pos_end=(-299.0, -201.0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 95
    wall = NormalWall(pos_start=(-303.0, -178.0),
                      pos_end=(-303.0, -201.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 96
    wall = NormalWall(pos_start=(100.0, -186.0),
                      pos_end=(206.0, -186.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 97
    wall = NormalWall(pos_start=(-544.0, -199.0),
                      pos_end=(388.0, -199.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 98
    wall = NormalWall(pos_start=(-545.0, -200.0),
                      pos_end=(388.0, -200.0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 99
    wall = NormalWall(pos_start=(-105.0, -368.0),
                      pos_end=(551.0, -368.0))
    playground.add(wall, wall.wall_coordinates)

