"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it a image of the map we want to create.
"""

from spg_overlay.normal_wall import NormalWall, NormalBox


# Dimension of the map : (750,1112)
# Dimension factor : 0.6732495511669659
def add_boxes(playground):
    # box 0
    playground.add_element(NormalBox(up_left_point=(657, 390),
                                     width=110, height=177))
    # box 1
    playground.add_element(NormalBox(up_left_point=(961, 367),
                                     width=17, height=17))
    # box 2
    playground.add_element(NormalBox(up_left_point=(634, 359),
                                     width=17, height=17))
    # box 3
    playground.add_element(NormalBox(up_left_point=(632, 240),
                                     width=17, height=17))
    # box 4
    playground.add_element(NormalBox(up_left_point=(957, 232),
                                     width=17, height=17))
    # box 5
    playground.add_element(NormalBox(up_left_point=(657, 24),
                                     width=111, height=184))
    # box 6
    playground.add_element(NormalBox(up_left_point=(516, 23),
                                     width=106, height=184))


def add_walls(playground):
    # wall 0
    playground.add_element(NormalWall(start_point=(4, 5),
                                      end_point=(4, 577)))
    # wall 1
    playground.add_element(NormalWall(start_point=(1112, 5),
                                      end_point=(5, 5)))
    # wall 2
    playground.add_element(NormalWall(start_point=(5, 79),
                                      end_point=(5, 7)))
    # wall 3
    playground.add_element(NormalWall(start_point=(6, 7),
                                      end_point=(137, 7)))
    # wall 4
    playground.add_element(NormalWall(start_point=(139, 16),
                                      end_point=(139, 7)))
    # wall 5
    playground.add_element(NormalWall(start_point=(139, 7),
                                      end_point=(199, 7)))
    # wall 6
    playground.add_element(NormalWall(start_point=(473, 7),
                                      end_point=(1111, 7)))
    # wall 7
    playground.add_element(NormalWall(start_point=(1112, 750),
                                      end_point=(1112, 7)))
    # wall 8
    playground.add_element(NormalWall(start_point=(137, 7),
                                      end_point=(137, 16)))
    # wall 9
    playground.add_element(NormalWall(start_point=(199, 7),
                                      end_point=(199, 148)))
    # wall 10
    playground.add_element(NormalWall(start_point=(201, 137),
                                      end_point=(201, 7)))
    # wall 11
    playground.add_element(NormalWall(start_point=(202, 7),
                                      end_point=(471, 7)))
    # wall 12
    playground.add_element(NormalWall(start_point=(471, 9),
                                      end_point=(471, 134)))
    # wall 13
    playground.add_element(NormalWall(start_point=(1111, 7),
                                      end_point=(1111, 750)))
    # wall 14
    playground.add_element(NormalWall(start_point=(473, 133),
                                      end_point=(473, 8)))
    # wall 15
    playground.add_element(NormalWall(start_point=(516, 24),
                                      end_point=(516, 205)))
    # wall 16
    playground.add_element(NormalWall(start_point=(619, 24),
                                      end_point=(518, 24)))
    # wall 17
    playground.add_element(NormalWall(start_point=(619, 205),
                                      end_point=(619, 25)))
    # wall 18
    playground.add_element(NormalWall(start_point=(658, 26),
                                      end_point=(658, 206)))
    # wall 19
    playground.add_element(NormalWall(start_point=(766, 25),
                                      end_point=(660, 25)))
    # wall 20
    playground.add_element(NormalWall(start_point=(766, 206),
                                      end_point=(766, 26)))
    # wall 21
    playground.add_element(NormalWall(start_point=(139, 90),
                                      end_point=(139, 67)))
    # wall 22
    playground.add_element(NormalWall(start_point=(137, 68),
                                      end_point=(137, 90)))
    # wall 23
    playground.add_element(NormalWall(start_point=(137, 79),
                                      end_point=(6, 79)))
    # wall 24
    playground.add_element(NormalWall(start_point=(5, 148),
                                      end_point=(5, 81)))
    # wall 25
    playground.add_element(NormalWall(start_point=(6, 81),
                                      end_point=(137, 81)))
    # wall 26
    playground.add_element(NormalWall(start_point=(401, 137),
                                      end_point=(201, 137)))
    # wall 27
    playground.add_element(NormalWall(start_point=(471, 137),
                                      end_point=(463, 137)))
    # wall 28
    playground.add_element(NormalWall(start_point=(139, 159),
                                      end_point=(139, 139)))
    # wall 29
    playground.add_element(NormalWall(start_point=(201, 148),
                                      end_point=(201, 139)))
    # wall 30
    playground.add_element(NormalWall(start_point=(201, 139),
                                      end_point=(295, 139)))
    # wall 31
    playground.add_element(NormalWall(start_point=(296, 156),
                                      end_point=(296, 139)))
    # wall 32
    playground.add_element(NormalWall(start_point=(297, 139),
                                      end_point=(389, 139)))
    # wall 33
    playground.add_element(NormalWall(start_point=(390, 409),
                                      end_point=(390, 139)))
    # wall 34
    playground.add_element(NormalWall(start_point=(391, 139),
                                      end_point=(401, 139)))
    # wall 35
    playground.add_element(NormalWall(start_point=(463, 139),
                                      end_point=(471, 139)))
    # wall 36
    playground.add_element(NormalWall(start_point=(137, 139),
                                      end_point=(137, 159)))
    # wall 37
    playground.add_element(NormalWall(start_point=(295, 139),
                                      end_point=(295, 156)))
    # wall 38
    playground.add_element(NormalWall(start_point=(389, 139),
                                      end_point=(389, 409)))
    # wall 39
    playground.add_element(NormalWall(start_point=(473, 152),
                                      end_point=(472, 142)))
    # wall 40
    playground.add_element(NormalWall(start_point=(471, 143),
                                      end_point=(471, 152)))
    # wall 41
    playground.add_element(NormalWall(start_point=(137, 148),
                                      end_point=(6, 148)))
    # wall 42
    playground.add_element(NormalWall(start_point=(5, 206),
                                      end_point=(5, 149)))
    # wall 43
    playground.add_element(NormalWall(start_point=(6, 149),
                                      end_point=(137, 149)))
    # wall 44
    playground.add_element(NormalWall(start_point=(139, 217),
                                      end_point=(139, 198)))
    # wall 45
    playground.add_element(NormalWall(start_point=(137, 199),
                                      end_point=(137, 217)))
    # wall 46
    playground.add_element(NormalWall(start_point=(518, 205),
                                      end_point=(619, 205)))
    # wall 47
    playground.add_element(NormalWall(start_point=(137, 206),
                                      end_point=(6, 206)))
    # wall 48
    playground.add_element(NormalWall(start_point=(473, 477),
                                      end_point=(473, 206)))
    # wall 49
    playground.add_element(NormalWall(start_point=(659, 206),
                                      end_point=(765, 206)))
    # wall 50
    playground.add_element(NormalWall(start_point=(471, 207),
                                      end_point=(471, 477)))
    # wall 51
    playground.add_element(NormalWall(start_point=(5, 265),
                                      end_point=(5, 207)))
    # wall 52
    playground.add_element(NormalWall(start_point=(6, 207),
                                      end_point=(137, 207)))
    # wall 53
    playground.add_element(NormalWall(start_point=(296, 333),
                                      end_point=(296, 215)))
    # wall 54
    playground.add_element(NormalWall(start_point=(295, 215),
                                      end_point=(295, 333)))
    # wall 55
    playground.add_element(NormalWall(start_point=(201, 231),
                                      end_point=(200, 219)))
    # wall 56
    playground.add_element(NormalWall(start_point=(222, 231),
                                      end_point=(202, 231)))
    # wall 57
    playground.add_element(NormalWall(start_point=(199, 220),
                                      end_point=(199, 409)))
    # wall 58
    playground.add_element(NormalWall(start_point=(294, 231),
                                      end_point=(283, 231)))
    # wall 59
    playground.add_element(NormalWall(start_point=(316, 231),
                                      end_point=(297, 231)))
    # wall 60
    playground.add_element(NormalWall(start_point=(388, 231),
                                      end_point=(374, 231)))
    # wall 61
    playground.add_element(NormalWall(start_point=(201, 322),
                                      end_point=(201, 232)))
    # wall 62
    playground.add_element(NormalWall(start_point=(201, 232),
                                      end_point=(221, 232)))
    # wall 63
    playground.add_element(NormalWall(start_point=(283, 232),
                                      end_point=(294, 232)))
    # wall 64
    playground.add_element(NormalWall(start_point=(297, 232),
                                      end_point=(316, 232)))
    # wall 65
    playground.add_element(NormalWall(start_point=(374, 232),
                                      end_point=(388, 232)))
    # wall 66
    playground.add_element(NormalWall(start_point=(957, 234),
                                      end_point=(957, 247)))
    # wall 67
    playground.add_element(NormalWall(start_point=(972, 233),
                                      end_point=(959, 233)))
    # wall 68
    playground.add_element(NormalWall(start_point=(971, 247),
                                      end_point=(971, 234)))
    # wall 69
    playground.add_element(NormalWall(start_point=(632, 241),
                                      end_point=(632, 254)))
    # wall 70
    playground.add_element(NormalWall(start_point=(646, 240),
                                      end_point=(634, 240)))
    # wall 71
    playground.add_element(NormalWall(start_point=(646, 254),
                                      end_point=(646, 242)))
    # wall 72
    playground.add_element(NormalWall(start_point=(959, 247),
                                      end_point=(971, 247)))
    # wall 73
    playground.add_element(NormalWall(start_point=(139, 338),
                                      end_point=(139, 254)))
    # wall 74
    playground.add_element(NormalWall(start_point=(634, 254),
                                      end_point=(646, 254)))
    # wall 75
    playground.add_element(NormalWall(start_point=(137, 255),
                                      end_point=(137, 265)))
    # wall 76
    playground.add_element(NormalWall(start_point=(5, 326),
                                      end_point=(5, 267)))
    # wall 77
    playground.add_element(NormalWall(start_point=(137, 267),
                                      end_point=(137, 338)))
    # wall 78
    playground.add_element(NormalWall(start_point=(294, 322),
                                      end_point=(201, 322)))
    # wall 79
    playground.add_element(NormalWall(start_point=(316, 322),
                                      end_point=(297, 322)))
    # wall 80
    playground.add_element(NormalWall(start_point=(388, 322),
                                      end_point=(374, 322)))
    # wall 81
    playground.add_element(NormalWall(start_point=(201, 396),
                                      end_point=(201, 323)))
    # wall 82
    playground.add_element(NormalWall(start_point=(201, 323),
                                      end_point=(294, 323)))
    # wall 83
    playground.add_element(NormalWall(start_point=(297, 323),
                                      end_point=(316, 323)))
    # wall 84
    playground.add_element(NormalWall(start_point=(374, 323),
                                      end_point=(388, 323)))
    # wall 85
    playground.add_element(NormalWall(start_point=(137, 326),
                                      end_point=(6, 326)))
    # wall 86
    playground.add_element(NormalWall(start_point=(5, 386),
                                      end_point=(5, 327)))
    # wall 87
    playground.add_element(NormalWall(start_point=(6, 327),
                                      end_point=(137, 327)))
    # wall 88
    playground.add_element(NormalWall(start_point=(634, 360),
                                      end_point=(634, 374)))
    # wall 89
    playground.add_element(NormalWall(start_point=(648, 360),
                                      end_point=(636, 359)))
    # wall 90
    playground.add_element(NormalWall(start_point=(648, 374),
                                      end_point=(648, 361)))
    # wall 91
    playground.add_element(NormalWall(start_point=(961, 368),
                                      end_point=(961, 382)))
    # wall 92
    playground.add_element(NormalWall(start_point=(976, 368),
                                      end_point=(963, 368)))
    # wall 93
    playground.add_element(NormalWall(start_point=(976, 382),
                                      end_point=(976, 369)))
    # wall 94
    playground.add_element(NormalWall(start_point=(636, 374),
                                      end_point=(648, 374)))
    # wall 95
    playground.add_element(NormalWall(start_point=(139, 411),
                                      end_point=(139, 380)))
    # wall 96
    playground.add_element(NormalWall(start_point=(137, 380),
                                      end_point=(137, 411)))
    # wall 97
    playground.add_element(NormalWall(start_point=(963, 382),
                                      end_point=(975, 382)))
    # wall 98
    playground.add_element(NormalWall(start_point=(137, 386),
                                      end_point=(6, 386)))
    # wall 99
    playground.add_element(NormalWall(start_point=(296, 396),
                                      end_point=(296, 386)))
    # wall 100
    playground.add_element(NormalWall(start_point=(316, 396),
                                      end_point=(298, 396)))
    # wall 101
    playground.add_element(NormalWall(start_point=(295, 387),
                                      end_point=(295, 396)))
    # wall 102
    playground.add_element(NormalWall(start_point=(5, 576),
                                      end_point=(5, 388)))
    # wall 103
    playground.add_element(NormalWall(start_point=(6, 388),
                                      end_point=(137, 388)))
    # wall 104
    playground.add_element(NormalWall(start_point=(658, 392),
                                      end_point=(658, 566)))
    # wall 105
    playground.add_element(NormalWall(start_point=(765, 391),
                                      end_point=(660, 391)))
    # wall 106
    playground.add_element(NormalWall(start_point=(765, 566),
                                      end_point=(765, 393)))
    # wall 107
    playground.add_element(NormalWall(start_point=(294, 396),
                                      end_point=(201, 396)))
    # wall 108
    playground.add_element(NormalWall(start_point=(388, 396),
                                      end_point=(374, 396)))
    # wall 109
    playground.add_element(NormalWall(start_point=(201, 409),
                                      end_point=(201, 397)))
    # wall 110
    playground.add_element(NormalWall(start_point=(201, 397),
                                      end_point=(316, 397)))
    # wall 111
    playground.add_element(NormalWall(start_point=(374, 397),
                                      end_point=(388, 397)))
    # wall 112
    playground.add_element(NormalWall(start_point=(139, 481),
                                      end_point=(139, 463)))
    # wall 113
    playground.add_element(NormalWall(start_point=(137, 464),
                                      end_point=(137, 579)))
    # wall 114
    playground.add_element(NormalWall(start_point=(201, 477),
                                      end_point=(200, 466)))
    # wall 115
    playground.add_element(NormalWall(start_point=(471, 477),
                                      end_point=(202, 477)))
    # wall 116
    playground.add_element(NormalWall(start_point=(391, 476),
                                      end_point=(390, 466)))
    # wall 117
    playground.add_element(NormalWall(start_point=(199, 467),
                                      end_point=(199, 477)))
    # wall 118
    playground.add_element(NormalWall(start_point=(389, 467),
                                      end_point=(389, 476)))
    # wall 119
    playground.add_element(NormalWall(start_point=(201, 478),
                                      end_point=(253, 478)))
    # wall 120
    playground.add_element(NormalWall(start_point=(254, 502),
                                      end_point=(254, 478)))
    # wall 121
    playground.add_element(NormalWall(start_point=(255, 478),
                                      end_point=(424, 478)))
    # wall 122
    playground.add_element(NormalWall(start_point=(425, 576),
                                      end_point=(425, 478)))
    # wall 123
    playground.add_element(NormalWall(start_point=(426, 478),
                                      end_point=(471, 478)))
    # wall 124
    playground.add_element(NormalWall(start_point=(253, 479),
                                      end_point=(253, 502)))
    # wall 125
    playground.add_element(NormalWall(start_point=(424, 479),
                                      end_point=(424, 576)))
    # wall 126
    playground.add_element(NormalWall(start_point=(139, 579),
                                      end_point=(139, 483)))
    # wall 127
    playground.add_element(NormalWall(start_point=(39, 483),
                                      end_point=(6, 483)))
    # wall 128
    playground.add_element(NormalWall(start_point=(137, 483),
                                      end_point=(109, 483)))
    # wall 129
    playground.add_element(NormalWall(start_point=(6, 485),
                                      end_point=(38, 485)))
    # wall 130
    playground.add_element(NormalWall(start_point=(108, 485),
                                      end_point=(137, 485)))
    # wall 131
    playground.add_element(NormalWall(start_point=(254, 576),
                                      end_point=(254, 556)))
    # wall 132
    playground.add_element(NormalWall(start_point=(423, 576),
                                      end_point=(256, 576)))
    # wall 133
    playground.add_element(NormalWall(start_point=(252, 557),
                                      end_point=(252, 576)))
    # wall 134
    playground.add_element(NormalWall(start_point=(250, 576),
                                      end_point=(139, 576)))
    # wall 135
    playground.add_element(NormalWall(start_point=(659, 566),
                                      end_point=(764, 566)))
    # wall 136
    playground.add_element(NormalWall(start_point=(137, 576),
                                      end_point=(6, 576)))
    # wall 137
    playground.add_element(NormalWall(start_point=(948, 576),
                                      end_point=(426, 576)))
    # wall 138
    playground.add_element(NormalWall(start_point=(5, 578),
                                      end_point=(137, 578)))
    # wall 139
    playground.add_element(NormalWall(start_point=(139, 578),
                                      end_point=(252, 578)))
    # wall 140
    playground.add_element(NormalWall(start_point=(254, 578),
                                      end_point=(947, 578)))
    # wall 141
    playground.add_element(NormalWall(start_point=(1110, 747),
                                      end_point=(452, 747)))
    # wall 142
    playground.add_element(NormalWall(start_point=(451, 749),
                                      end_point=(1110, 749)))
