"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the
map we want to create.
"""
import pathlib
import sys

# Insert the parent directory of the current file's directory into sys.path.
# This allows Python to locate modules that are one level above the current
# script, in this case simulation.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from swarm_rescue.simulation.elements.normal_wall import NormalWall


# Dimension of the map : (1700, 1100)
# Dimension factor : 1.0
def add_boxes(playground):
    pass


def add_walls(playground):
    # vertical wall 0
    wall = NormalWall(pos_start=(-681, 547),
                      pos_end=(-681, 318))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 1
    wall = NormalWall(pos_start=(-677, 547),
                      pos_end=(-677, 318))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 2
    wall = NormalWall(pos_start=(-498, 547),
                      pos_end=(-498, 318))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 3
    wall = NormalWall(pos_start=(-494, 547),
                      pos_end=(-494, 318))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 4
    wall = NormalWall(pos_start=(242, 547),
                      pos_end=(242, 318))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 5
    wall = NormalWall(pos_start=(246, 547),
                      pos_end=(246, 318))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 6
    wall = NormalWall(pos_start=(418, 547),
                      pos_end=(418, 318))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 7
    wall = NormalWall(pos_start=(422, 547),
                      pos_end=(422, 318))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 8
    wall = NormalWall(pos_start=(626, 547),
                      pos_end=(626, 318))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 9
    wall = NormalWall(pos_start=(630, 547),
                      pos_end=(630, 318))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 10
    wall = NormalWall(pos_start=(-840, 545),
                      pos_end=(844, 545))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 11
    wall = NormalWall(pos_start=(-323, 460),
                      pos_end=(67, 460))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 12
    wall = NormalWall(pos_start=(68, 469),
                      pos_end=(68, 318))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 13
    wall = NormalWall(pos_start=(-325, 470),
                      pos_end=(-325, 318))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 14
    wall = NormalWall(pos_start=(-136, 459),
                      pos_end=(-136, 318))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 15
    wall = NormalWall(pos_start=(-323, 456),
                      pos_end=(67, 456))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 16
    wall = NormalWall(pos_start=(64, 458),
                      pos_end=(64, 318))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 17
    wall = NormalWall(pos_start=(-321, 459),
                      pos_end=(-321, 318))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 18
    wall = NormalWall(pos_start=(-132, 459),
                      pos_end=(-132, 318))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 19
    wall = NormalWall(pos_start=(-847, 321),
                      pos_end=(-783, 321))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 20
    wall = NormalWall(pos_start=(-679, 321),
                      pos_end=(-598, 321))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 21
    wall = NormalWall(pos_start=(-393, 321),
                      pos_end=(-269, 321))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 22
    wall = NormalWall(pos_start=(-179, 321),
                      pos_end=(-82, 321))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 23
    wall = NormalWall(pos_start=(8, 321),
                      pos_end=(136, 321))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 24
    wall = NormalWall(pos_start=(350, 321),
                      pos_end=(473, 321))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 25
    wall = NormalWall(pos_start=(563, 321),
                      pos_end=(697, 321))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 26
    wall = NormalWall(pos_start=(787, 321),
                      pos_end=(846, 321))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 27
    wall = NormalWall(pos_start=(-847, 317),
                      pos_end=(-783, 317))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 28
    wall = NormalWall(pos_start=(-693, 317),
                      pos_end=(-598, 317))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 29
    wall = NormalWall(pos_start=(-508, 318),
                      pos_end=(-484, 318))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 30
    wall = NormalWall(pos_start=(-393, 317),
                      pos_end=(-269, 317))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 31
    wall = NormalWall(pos_start=(-179, 317),
                      pos_end=(-82, 317))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 32
    wall = NormalWall(pos_start=(8, 317),
                      pos_end=(136, 317))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 33
    wall = NormalWall(pos_start=(227, 317),
                      pos_end=(259, 317))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 34
    wall = NormalWall(pos_start=(350, 317),
                      pos_end=(473, 317))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 35
    wall = NormalWall(pos_start=(563, 317),
                      pos_end=(697, 317))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 36
    wall = NormalWall(pos_start=(787, 317),
                      pos_end=(846, 317))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 37
    wall = NormalWall(pos_start=(-847, 233),
                      pos_end=(-757, 233))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 38
    wall = NormalWall(pos_start=(-667, 233),
                      pos_end=(-390, 233))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 39
    wall = NormalWall(pos_start=(-300, 233),
                      pos_end=(-80, 233))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 40
    wall = NormalWall(pos_start=(10, 233),
                      pos_end=(261, 233))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 41
    wall = NormalWall(pos_start=(351, 233),
                      pos_end=(632, 233))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 42
    wall = NormalWall(pos_start=(722, 233),
                      pos_end=(846, 233))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 43
    wall = NormalWall(pos_start=(-847, 229),
                      pos_end=(-757, 229))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 44
    wall = NormalWall(pos_start=(-667, 229),
                      pos_end=(-530, 229))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 45
    wall = NormalWall(pos_start=(-532, 229),
                      pos_end=(-390, 229))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 46
    wall = NormalWall(pos_start=(-300, 229),
                      pos_end=(-221, 229))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 47
    wall = NormalWall(pos_start=(-224, 231),
                      pos_end=(-224, -15))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 48
    wall = NormalWall(pos_start=(-223, 229),
                      pos_end=(-80, 229))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 49
    wall = NormalWall(pos_start=(-220, 231),
                      pos_end=(-220, -15))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 50
    wall = NormalWall(pos_start=(10, 229),
                      pos_end=(120, 229))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 51
    wall = NormalWall(pos_start=(117, 231),
                      pos_end=(117, -15))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 52
    wall = NormalWall(pos_start=(118, 229),
                      pos_end=(261, 229))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 53
    wall = NormalWall(pos_start=(121, 231),
                      pos_end=(121, -15))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 54
    wall = NormalWall(pos_start=(351, 229),
                      pos_end=(492, 229))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 55
    wall = NormalWall(pos_start=(490, 229),
                      pos_end=(632, 229))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 56
    wall = NormalWall(pos_start=(722, 229),
                      pos_end=(846, 229))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 57
    wall = NormalWall(pos_start=(669, 133),
                      pos_end=(669, 95))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 58
    wall = NormalWall(pos_start=(282, 135),
                      pos_end=(282, 91))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 59
    wall = NormalWall(pos_start=(283, 132),
                      pos_end=(673, 132))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 60
    wall = NormalWall(pos_start=(489, 231),
                      pos_end=(489, -15))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 61
    wall = NormalWall(pos_start=(283, 128),
                      pos_end=(673, 128))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 62
    wall = NormalWall(pos_start=(665, 133),
                      pos_end=(665, 95))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 63
    wall = NormalWall(pos_start=(286, 135),
                      pos_end=(286, 91))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 64
    wall = NormalWall(pos_start=(493, 231),
                      pos_end=(493, -15))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 65
    wall = NormalWall(pos_start=(-349, 126),
                      pos_end=(-349, 84))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 66
    wall = NormalWall(pos_start=(-695, 128),
                      pos_end=(-695, 82))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 67
    wall = NormalWall(pos_start=(-694, 125),
                      pos_end=(-346, 125))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 68
    wall = NormalWall(pos_start=(-533, 231),
                      pos_end=(-533, -15))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 69
    wall = NormalWall(pos_start=(-694, 121),
                      pos_end=(-346, 121))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 70
    wall = NormalWall(pos_start=(-353, 126),
                      pos_end=(-353, 84))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 71
    wall = NormalWall(pos_start=(-691, 128),
                      pos_end=(-691, 82))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 72
    wall = NormalWall(pos_start=(-529, 231),
                      pos_end=(-529, -15))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 73
    wall = NormalWall(pos_start=(-847, -12),
                      pos_end=(-418, -12))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 74
    wall = NormalWall(pos_start=(-300, -12),
                      pos_end=(236, -12))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 75
    wall = NormalWall(pos_start=(368, -12),
                      pos_end=(846, -12))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 76
    wall = NormalWall(pos_start=(-847, -16),
                      pos_end=(-530, -16))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 77
    wall = NormalWall(pos_start=(-537, -16),
                      pos_end=(-418, -16))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 78
    wall = NormalWall(pos_start=(-300, -16),
                      pos_end=(236, -16))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 79
    wall = NormalWall(pos_start=(368, -16),
                      pos_end=(846, -16))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 80
    wall = NormalWall(pos_start=(843, 547),
                      pos_end=(843, -546))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 81
    wall = NormalWall(pos_start=(121, -148),
                      pos_end=(121, -546))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 82
    wall = NormalWall(pos_start=(122, -151),
                      pos_end=(263, -151))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 83
    wall = NormalWall(pos_start=(358, -151),
                      pos_end=(459, -151))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 84
    wall = NormalWall(pos_start=(456, -149),
                      pos_end=(456, -355))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 85
    wall = NormalWall(pos_start=(122, -155),
                      pos_end=(263, -155))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 86
    wall = NormalWall(pos_start=(358, -155),
                      pos_end=(459, -155))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 87
    wall = NormalWall(pos_start=(452, -149),
                      pos_end=(452, -355))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 88
    wall = NormalWall(pos_start=(640, -152),
                      pos_end=(640, -173))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 89
    wall = NormalWall(pos_start=(641, -155),
                      pos_end=(661, -155))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 90
    wall = NormalWall(pos_start=(657, -154),
                      pos_end=(657, -176))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 91
    wall = NormalWall(pos_start=(-847, -163),
                      pos_end=(-802, -163))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 92
    wall = NormalWall(pos_start=(-712, -163),
                      pos_end=(-438, -163))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 93
    wall = NormalWall(pos_start=(-441, -161),
                      pos_end=(-441, -209))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 94
    wall = NormalWall(pos_start=(-158, -162),
                      pos_end=(-158, -183))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 95
    wall = NormalWall(pos_start=(-157, -165),
                      pos_end=(-137, -165))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 96
    wall = NormalWall(pos_start=(-141, -164),
                      pos_end=(-141, -186))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 97
    wall = NormalWall(pos_start=(-847, -167),
                      pos_end=(-802, -167))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 98
    wall = NormalWall(pos_start=(-845, 547),
                      pos_end=(-845, -544))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 99
    wall = NormalWall(pos_start=(-661, -164),
                      pos_end=(-661, -462))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 100
    wall = NormalWall(pos_start=(-712, -167),
                      pos_end=(-438, -167))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 101
    wall = NormalWall(pos_start=(-445, -161),
                      pos_end=(-445, -209))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 102
    wall = NormalWall(pos_start=(-657, -164),
                      pos_end=(-657, -462))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 103
    wall = NormalWall(pos_start=(638, -172),
                      pos_end=(660, -172))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 104
    wall = NormalWall(pos_start=(-160, -182),
                      pos_end=(-138, -182))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 105
    wall = NormalWall(pos_start=(231, -352),
                      pos_end=(298, -352))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 106
    wall = NormalWall(pos_start=(299, -263),
                      pos_end=(299, -546))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 107
    wall = NormalWall(pos_start=(-155, -265),
                      pos_end=(-155, -286))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 108
    wall = NormalWall(pos_start=(-154, -268),
                      pos_end=(-134, -268))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 109
    wall = NormalWall(pos_start=(-138, -267),
                      pos_end=(-138, -289))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 110
    wall = NormalWall(pos_start=(-157, -285),
                      pos_end=(-135, -285))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 111
    wall = NormalWall(pos_start=(123, -352),
                      pos_end=(141, -352))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 112
    wall = NormalWall(pos_start=(125, -148),
                      pos_end=(125, -546))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 113
    wall = NormalWall(pos_start=(231, -356),
                      pos_end=(298, -356))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 114
    wall = NormalWall(pos_start=(295, -263),
                      pos_end=(295, -546))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 115
    wall = NormalWall(pos_start=(-155, -372),
                      pos_end=(-155, -393))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 116
    wall = NormalWall(pos_start=(-154, -375),
                      pos_end=(-134, -375))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 117
    wall = NormalWall(pos_start=(-138, -374),
                      pos_end=(-138, -396))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 118
    wall = NormalWall(pos_start=(-157, -392),
                      pos_end=(-135, -392))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 119
    wall = NormalWall(pos_start=(452, -466),
                      pos_end=(452, -546))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 120
    wall = NormalWall(pos_start=(456, -466),
                      pos_end=(456, -546))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 121
    wall = NormalWall(pos_start=(-152, -475),
                      pos_end=(-152, -496))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 122
    wall = NormalWall(pos_start=(-151, -478),
                      pos_end=(-131, -478))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 123
    wall = NormalWall(pos_start=(-135, -477),
                      pos_end=(-135, -499))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 124
    wall = NormalWall(pos_start=(-154, -495),
                      pos_end=(-132, -495))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 125
    wall = NormalWall(pos_start=(-445, -499),
                      pos_end=(-445, -546))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 126
    wall = NormalWall(pos_start=(-441, -499),
                      pos_end=(-441, -546))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 127
    wall = NormalWall(pos_start=(-846, -543),
                      pos_end=(845, -543))
    playground.add(wall, wall.wall_coordinates)


    # AJOUT MANUEL du mur en pointillé, car ne peut pas être généré automatiquement.
    for y in range(-502, -211, 20):
        wall = NormalWall(pos_start=(-442, y),
                          pos_end=(-442, y - 10))
        playground.add(wall, wall.wall_coordinates)
