"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the map we want to create.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1660, 1122)
# Dimension factor : 1.0
def add_boxes(playground):
    # box 0
    box = NormalBox(up_left_point=(149, -22),
                    width=163, height=228)
    playground.add(box, box.wall_coordinates)

    # box 1
    box = NormalBox(up_left_point=(176, 490),
                    width=138, height=241)
    playground.add(box, box.wall_coordinates)

    # box 2
    box = NormalBox(up_left_point=(-44, 490),
                    width=140, height=239)
    playground.add(box, box.wall_coordinates)


def add_walls(playground):
    # vertical wall 0
    wall = NormalWall(pos_start=(-821, 551),
                      pos_end=(-821, -554))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 1
    wall = NormalWall(pos_start=(-532, 550),
                      pos_end=(-532, 352))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 2
    wall = NormalWall(pos_start=(-126, 552),
                      pos_end=(-126, 333))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 3
    wall = NormalWall(pos_start=(822, 550),
                      pos_end=(822, -553))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 4
    wall = NormalWall(pos_start=(-530, 551),
                      pos_end=(-530, 353))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 5
    wall = NormalWall(pos_start=(-820, 550),
                      pos_end=(824, 550))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 6
    wall = NormalWall(pos_start=(-128, 549),
                      pos_end=(-128, 334))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 7
    wall = NormalWall(pos_start=(-42, 489),
                      pos_end=(-42, 255))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 8
    wall = NormalWall(pos_start=(-41, 488),
                      pos_end=(92, 488))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 9
    wall = NormalWall(pos_start=(90, 488),
                      pos_end=(90, 255))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 10
    wall = NormalWall(pos_start=(178, 489),
                      pos_end=(178, 253))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 11
    wall = NormalWall(pos_start=(179, 488),
                      pos_end=(310, 488))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 12
    wall = NormalWall(pos_start=(308, 488),
                      pos_end=(308, 253))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 13
    wall = NormalWall(pos_start=(-821, 441),
                      pos_end=(-631, 441))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 14
    wall = NormalWall(pos_start=(-821, 439),
                      pos_end=(-632, 439))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 15
    wall = NormalWall(pos_start=(-531, 355),
                      pos_end=(-247, 355))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 16
    wall = NormalWall(pos_start=(-532, 353),
                      pos_end=(-248, 353))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 17
    wall = NormalWall(pos_start=(-248, 355),
                      pos_end=(-248, -49))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 18
    wall = NormalWall(pos_start=(-250, 354),
                      pos_end=(-250, -49))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 19
    wall = NormalWall(pos_start=(-821, 339),
                      pos_end=(-631, 339))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 20
    wall = NormalWall(pos_start=(-821, 337),
                      pos_end=(-632, 337))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 21
    wall = NormalWall(pos_start=(-42, 257),
                      pos_end=(91, 257))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 22
    wall = NormalWall(pos_start=(178, 255),
                      pos_end=(309, 255))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 23
    wall = NormalWall(pos_start=(-821, 253),
                      pos_end=(-631, 253))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 24
    wall = NormalWall(pos_start=(-821, 251),
                      pos_end=(-632, 251))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 25
    wall = NormalWall(pos_start=(-388, 240),
                      pos_end=(-388, 79))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 26
    wall = NormalWall(pos_start=(-390, 239),
                      pos_end=(-390, 79))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 27
    wall = NormalWall(pos_start=(-530, 81),
                      pos_end=(-389, 81))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 28
    wall = NormalWall(pos_start=(-532, 232),
                      pos_end=(-532, -32))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 29
    wall = NormalWall(pos_start=(596, 212),
                      pos_end=(596, 192))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 30
    wall = NormalWall(pos_start=(597, 211),
                      pos_end=(615, 211))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 31
    wall = NormalWall(pos_start=(613, 211),
                      pos_end=(613, 192))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 32
    wall = NormalWall(pos_start=(596, 194),
                      pos_end=(614, 194))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 33
    wall = NormalWall(pos_start=(-126, 193),
                      pos_end=(-126, -151))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 34
    wall = NormalWall(pos_start=(-128, 192),
                      pos_end=(-128, -151))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 35
    wall = NormalWall(pos_start=(-622, 155),
                      pos_end=(-622, 73))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 36
    wall = NormalWall(pos_start=(-624, 154),
                      pos_end=(-624, 73))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 37
    wall = NormalWall(pos_start=(-530, 233),
                      pos_end=(-530, -31))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 38
    wall = NormalWall(pos_start=(-531, 79),
                      pos_end=(-388, 79))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 39
    wall = NormalWall(pos_start=(-821, 75),
                      pos_end=(-623, 75))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 40
    wall = NormalWall(pos_start=(-821, 73),
                      pos_end=(-622, 73))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 41
    wall = NormalWall(pos_start=(602, 12),
                      pos_end=(602, -8))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 42
    wall = NormalWall(pos_start=(603, 11),
                      pos_end=(621, 11))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 43
    wall = NormalWall(pos_start=(619, 11),
                      pos_end=(619, -8))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 44
    wall = NormalWall(pos_start=(602, -6),
                      pos_end=(620, -6))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 45
    wall = NormalWall(pos_start=(-821, -15),
                      pos_end=(-630, -15))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 46
    wall = NormalWall(pos_start=(-821, -17),
                      pos_end=(-631, -17))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 47
    wall = NormalWall(pos_start=(151, -23),
                      pos_end=(151, -246))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 48
    wall = NormalWall(pos_start=(152, -24),
                      pos_end=(308, -24))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 49
    wall = NormalWall(pos_start=(306, -24),
                      pos_end=(306, -246))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 50
    wall = NormalWall(pos_start=(-531, -29),
                      pos_end=(-386, -29))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 51
    wall = NormalWall(pos_start=(-532, -31),
                      pos_end=(-387, -31))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 52
    wall = NormalWall(pos_start=(-622, -133),
                      pos_end=(-622, -299))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 53
    wall = NormalWall(pos_start=(-624, -134),
                      pos_end=(-624, -299))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 54
    wall = NormalWall(pos_start=(-523, -149),
                      pos_end=(-127, -149))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 55
    wall = NormalWall(pos_start=(-450, -149),
                      pos_end=(-450, -180))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 56
    wall = NormalWall(pos_start=(-196, -149),
                      pos_end=(-196, -298))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 57
    wall = NormalWall(pos_start=(-524, -151),
                      pos_end=(-126, -151))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 58
    wall = NormalWall(pos_start=(-452, -150),
                      pos_end=(-452, -180))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 59
    wall = NormalWall(pos_start=(-198, -150),
                      pos_end=(-198, -298))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 60
    wall = NormalWall(pos_start=(-821, -159),
                      pos_end=(-791, -159))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 61
    wall = NormalWall(pos_start=(-653, -159),
                      pos_end=(-623, -159))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 62
    wall = NormalWall(pos_start=(-821, -161),
                      pos_end=(-792, -161))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 63
    wall = NormalWall(pos_start=(-654, -161),
                      pos_end=(-623, -161))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 64
    wall = NormalWall(pos_start=(151, -244),
                      pos_end=(307, -244))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 65
    wall = NormalWall(pos_start=(-821, -297),
                      pos_end=(542, -297))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 66
    wall = NormalWall(pos_start=(-821, -299),
                      pos_end=(541, -299))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 67
    wall = NormalWall(pos_start=(-821, -551),
                      pos_end=(823, -551))
    playground.add(wall, wall.wall_coordinates)
