"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the
map we want to create.
"""
import pathlib
import sys

# Insert the parent directory of the current file's directory into sys.path.
# This allows Python to locate modules that are one level above the current
# script, in this case simulation.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from swarm_rescue.simulation.elements.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1700, 1100)
# Dimension factor : 1.0
def add_boxes(playground):
    # box 0
    box = NormalBox(up_left_point=(-367, -272),
                    width=171, height=48)
    playground.add(box, box.wall_coordinates)

    # box 1
    box = NormalBox(up_left_point=(-344, 86),
                    width=93, height=50)
    playground.add(box, box.wall_coordinates)


def add_walls(playground):
    # vertical wall 0
    wall = NormalWall(pos_start=(-643, 541),
                      pos_end=(-643, 437))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 1
    wall = NormalWall(pos_start=(-640, 541),
                      pos_end=(-640, 484))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 2
    wall = NormalWall(pos_start=(-249, 541),
                      pos_end=(-249, 486))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 3
    wall = NormalWall(pos_start=(-246, 541),
                      pos_end=(-246, 437))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 4
    wall = NormalWall(pos_start=(396, 541),
                      pos_end=(396, 502))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 5
    wall = NormalWall(pos_start=(399, 541),
                      pos_end=(399, 502))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 6
    wall = NormalWall(pos_start=(-836, 539),
                      pos_end=(840, 539))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 7
    wall = NormalWall(pos_start=(-642, 487),
                      pos_end=(-607, 487))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 8
    wall = NormalWall(pos_start=(-611, 488),
                      pos_end=(-611, 461))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 9
    wall = NormalWall(pos_start=(-564, 490),
                      pos_end=(-564, 461))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 10
    wall = NormalWall(pos_start=(-563, 487),
                      pos_end=(-538, 487))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 11
    wall = NormalWall(pos_start=(-542, 489),
                      pos_end=(-542, 461))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 12
    wall = NormalWall(pos_start=(-498, 490),
                      pos_end=(-498, 461))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 13
    wall = NormalWall(pos_start=(-497, 487),
                      pos_end=(-472, 487))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 14
    wall = NormalWall(pos_start=(-476, 489),
                      pos_end=(-476, 461))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 15
    wall = NormalWall(pos_start=(-433, 490),
                      pos_end=(-433, 461))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 16
    wall = NormalWall(pos_start=(-432, 487),
                      pos_end=(-407, 487))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 17
    wall = NormalWall(pos_start=(-411, 489),
                      pos_end=(-411, 461))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 18
    wall = NormalWall(pos_start=(-360, 490),
                      pos_end=(-360, 461))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 19
    wall = NormalWall(pos_start=(-359, 487),
                      pos_end=(-334, 487))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 20
    wall = NormalWall(pos_start=(-338, 489),
                      pos_end=(-338, 461))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 21
    wall = NormalWall(pos_start=(-279, 490),
                      pos_end=(-279, 461))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 22
    wall = NormalWall(pos_start=(-278, 487),
                      pos_end=(-249, 487))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 23
    wall = NormalWall(pos_start=(-640, 467),
                      pos_end=(-640, 437))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 24
    wall = NormalWall(pos_start=(-645, 465),
                      pos_end=(-608, 465))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 25
    wall = NormalWall(pos_start=(-566, 465),
                      pos_end=(-539, 465))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 26
    wall = NormalWall(pos_start=(-500, 465),
                      pos_end=(-473, 465))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 27
    wall = NormalWall(pos_start=(-435, 465),
                      pos_end=(-408, 465))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 28
    wall = NormalWall(pos_start=(-362, 465),
                      pos_end=(-335, 465))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 29
    wall = NormalWall(pos_start=(-281, 465),
                      pos_end=(-248, 465))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 30
    wall = NormalWall(pos_start=(-249, 467),
                      pos_end=(-249, 437))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 31
    wall = NormalWall(pos_start=(630, 454),
                      pos_end=(630, 335))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 32
    wall = NormalWall(pos_start=(633, 454),
                      pos_end=(633, 335))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 33
    wall = NormalWall(pos_start=(394, 338),
                      pos_end=(842, 338))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 34
    wall = NormalWall(pos_start=(396, 390),
                      pos_end=(396, 332))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 35
    wall = NormalWall(pos_start=(394, 335),
                      pos_end=(842, 335))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 36
    wall = NormalWall(pos_start=(839, 541),
                      pos_end=(839, -540))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 37
    wall = NormalWall(pos_start=(399, 390),
                      pos_end=(399, 332))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 38
    wall = NormalWall(pos_start=(310, 378),
                      pos_end=(310, 349))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 39
    wall = NormalWall(pos_start=(311, 375),
                      pos_end=(336, 375))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 40
    wall = NormalWall(pos_start=(332, 377),
                      pos_end=(332, 349))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 41
    wall = NormalWall(pos_start=(-761, 262),
                      pos_end=(-665, 262))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 42
    wall = NormalWall(pos_start=(-667, 353),
                      pos_end=(-90, 353))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 43
    wall = NormalWall(pos_start=(-93, 355),
                      pos_end=(-93, 260))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 44
    wall = NormalWall(pos_start=(308, 353),
                      pos_end=(335, 353))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 45
    wall = NormalWall(pos_start=(-498, 353),
                      pos_end=(-498, 174))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 46
    wall = NormalWall(pos_start=(-313, 353),
                      pos_end=(-313, 306))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 47
    wall = NormalWall(pos_start=(-667, 350),
                      pos_end=(-90, 350))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 48
    wall = NormalWall(pos_start=(-96, 355),
                      pos_end=(-96, 260))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 49
    wall = NormalWall(pos_start=(-665, 356),
                      pos_end=(-665, 81))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 50
    wall = NormalWall(pos_start=(-495, 353),
                      pos_end=(-495, 174))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 51
    wall = NormalWall(pos_start=(-310, 353),
                      pos_end=(-310, 306))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 52
    wall = NormalWall(pos_start=(614, 321),
                      pos_end=(614, 292))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 53
    wall = NormalWall(pos_start=(615, 318),
                      pos_end=(640, 318))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 54
    wall = NormalWall(pos_start=(636, 320),
                      pos_end=(636, 292))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 55
    wall = NormalWall(pos_start=(612, 296),
                      pos_end=(639, 296))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 56
    wall = NormalWall(pos_start=(-761, 259),
                      pos_end=(-665, 259))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 57
    wall = NormalWall(pos_start=(-668, 356),
                      pos_end=(-668, 81))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 58
    wall = NormalWall(pos_start=(207, 243),
                      pos_end=(207, 214))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 59
    wall = NormalWall(pos_start=(208, 240),
                      pos_end=(233, 240))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 60
    wall = NormalWall(pos_start=(229, 242),
                      pos_end=(229, 214))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 61
    wall = NormalWall(pos_start=(486, 225),
                      pos_end=(486, 196))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 62
    wall = NormalWall(pos_start=(487, 222),
                      pos_end=(512, 222))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 63
    wall = NormalWall(pos_start=(508, 224),
                      pos_end=(508, 196))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 64
    wall = NormalWall(pos_start=(-313, 225),
                      pos_end=(-313, 179))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 65
    wall = NormalWall(pos_start=(-498, 185),
                      pos_end=(-308, 185))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 66
    wall = NormalWall(pos_start=(-310, 225),
                      pos_end=(-310, 179))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 67
    wall = NormalWall(pos_start=(-409, 182),
                      pos_end=(-308, 182))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 68
    wall = NormalWall(pos_start=(-498, 182),
                      pos_end=(-402, 182))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 69
    wall = NormalWall(pos_start=(205, 218),
                      pos_end=(232, 218))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 70
    wall = NormalWall(pos_start=(484, 200),
                      pos_end=(511, 200))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 71
    wall = NormalWall(pos_start=(28, 187),
                      pos_end=(28, 158))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 72
    wall = NormalWall(pos_start=(29, 184),
                      pos_end=(54, 184))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 73
    wall = NormalWall(pos_start=(50, 186),
                      pos_end=(50, 158))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 74
    wall = NormalWall(pos_start=(-412, 84),
                      pos_end=(-93, 84))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 75
    wall = NormalWall(pos_start=(-93, 169),
                      pos_end=(-93, -317))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 76
    wall = NormalWall(pos_start=(26, 162),
                      pos_end=(53, 162))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 77
    wall = NormalWall(pos_start=(-412, 81),
                      pos_end=(-339, 81))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 78
    wall = NormalWall(pos_start=(-342, 83),
                      pos_end=(-342, 38))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 79
    wall = NormalWall(pos_start=(-343, 42),
                      pos_end=(-253, 42))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 80
    wall = NormalWall(pos_start=(-769, 84),
                      pos_end=(-528, 84))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 81
    wall = NormalWall(pos_start=(-668, 81),
                      pos_end=(-528, 81))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 82
    wall = NormalWall(pos_start=(-769, 81),
                      pos_end=(-665, 81))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 83
    wall = NormalWall(pos_start=(-256, 81),
                      pos_end=(-93, 81))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 84
    wall = NormalWall(pos_start=(-96, 169),
                      pos_end=(-96, -317))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 85
    wall = NormalWall(pos_start=(-257, 84),
                      pos_end=(-257, 39))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 86
    wall = NormalWall(pos_start=(328, 18),
                      pos_end=(328, -11))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 87
    wall = NormalWall(pos_start=(329, 15),
                      pos_end=(354, 15))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 88
    wall = NormalWall(pos_start=(350, 17),
                      pos_end=(350, -11))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 89
    wall = NormalWall(pos_start=(326, -7),
                      pos_end=(353, -7))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 90
    wall = NormalWall(pos_start=(-668, -8),
                      pos_end=(-668, -317))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 91
    wall = NormalWall(pos_start=(-668, -18),
                      pos_end=(-467, -18))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 92
    wall = NormalWall(pos_start=(-469, -16),
                      pos_end=(-469, -230))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 93
    wall = NormalWall(pos_start=(-765, -46),
                      pos_end=(-765, -243))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 94
    wall = NormalWall(pos_start=(-665, -48),
                      pos_end=(-665, -317))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 95
    wall = NormalWall(pos_start=(-670, -50),
                      pos_end=(-500, -50))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 96
    wall = NormalWall(pos_start=(-501, -48),
                      pos_end=(-501, -231))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 97
    wall = NormalWall(pos_start=(-503, -228),
                      pos_end=(-466, -228))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 98
    wall = NormalWall(pos_start=(-762, -46),
                      pos_end=(-762, -243))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 99
    wall = NormalWall(pos_start=(51, -54),
                      pos_end=(51, -83))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 100
    wall = NormalWall(pos_start=(52, -57),
                      pos_end=(77, -57))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 101
    wall = NormalWall(pos_start=(73, -55),
                      pos_end=(73, -83))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 102
    wall = NormalWall(pos_start=(49, -79),
                      pos_end=(76, -79))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 103
    wall = NormalWall(pos_start=(593, -158),
                      pos_end=(593, -187))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 104
    wall = NormalWall(pos_start=(594, -161),
                      pos_end=(619, -161))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 105
    wall = NormalWall(pos_start=(615, -159),
                      pos_end=(615, -187))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 106
    wall = NormalWall(pos_start=(208, -171),
                      pos_end=(208, -200))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 107
    wall = NormalWall(pos_start=(209, -174),
                      pos_end=(234, -174))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 108
    wall = NormalWall(pos_start=(230, -172),
                      pos_end=(230, -200))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 109
    wall = NormalWall(pos_start=(591, -183),
                      pos_end=(618, -183))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 110
    wall = NormalWall(pos_start=(206, -196),
                      pos_end=(233, -196))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 111
    wall = NormalWall(pos_start=(447, -255),
                      pos_end=(447, -284))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 112
    wall = NormalWall(pos_start=(448, -258),
                      pos_end=(473, -258))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 113
    wall = NormalWall(pos_start=(469, -256),
                      pos_end=(469, -284))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 114
    wall = NormalWall(pos_start=(-365, -271),
                      pos_end=(-365, -317))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 115
    wall = NormalWall(pos_start=(-843, -314),
                      pos_end=(-360, -314))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 116
    wall = NormalWall(pos_start=(-364, -274),
                      pos_end=(-198, -274))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 117
    wall = NormalWall(pos_start=(-202, -272),
                      pos_end=(-202, -314))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 118
    wall = NormalWall(pos_start=(-204, -314),
                      pos_end=(629, -314))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 119
    wall = NormalWall(pos_start=(445, -280),
                      pos_end=(472, -280))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 120
    wall = NormalWall(pos_start=(-843, -317),
                      pos_end=(-663, -317))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 121
    wall = NormalWall(pos_start=(-841, 541),
                      pos_end=(-841, -539))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 122
    wall = NormalWall(pos_start=(-670, -317),
                      pos_end=(-542, -317))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 123
    wall = NormalWall(pos_start=(-545, -315),
                      pos_end=(-545, -367))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 124
    wall = NormalWall(pos_start=(-547, -365),
                      pos_end=(-185, -365))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 125
    wall = NormalWall(pos_start=(-545, -317),
                      pos_end=(-360, -317))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 126
    wall = NormalWall(pos_start=(-542, -315),
                      pos_end=(-542, -367))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 127
    wall = NormalWall(pos_start=(-96, -314),
                      pos_end=(-96, -364))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 128
    wall = NormalWall(pos_start=(-367, -317),
                      pos_end=(629, -317))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 129
    wall = NormalWall(pos_start=(-93, -314),
                      pos_end=(-93, -364))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 130
    wall = NormalWall(pos_start=(-547, -362),
                      pos_end=(-185, -362))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 131
    wall = NormalWall(pos_start=(-545, -485),
                      pos_end=(-545, -541))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 132
    wall = NormalWall(pos_start=(-544, -488),
                      pos_end=(-184, -488))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 133
    wall = NormalWall(pos_start=(-544, -491),
                      pos_end=(-184, -491))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 134
    wall = NormalWall(pos_start=(-542, -485),
                      pos_end=(-542, -541))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 135
    wall = NormalWall(pos_start=(-96, -489),
                      pos_end=(-96, -541))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 136
    wall = NormalWall(pos_start=(-93, -489),
                      pos_end=(-93, -541))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 137
    wall = NormalWall(pos_start=(-842, -538),
                      pos_end=(841, -538))
    playground.add(wall, wall.wall_coordinates)

