"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the
map we want to create.
"""
import pathlib
import sys

# Insert the parent directory of the current file's directory into sys.path.
# This allows Python to locate modules that are one level above the current
# script, in this case simulation.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from swarm_rescue.simulation.elements.normal_wall import NormalWall


# Dimension of the map : (1700, 1100)
# Dimension factor : 1.0
def add_boxes(playground):
    pass


def add_walls(playground):
    # vertical wall 0
    wall = NormalWall(pos_start=(-845, 547),
                      pos_end=(-845, -544))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 1
    wall = NormalWall(pos_start=(-840, 545),
                      pos_end=(-462, 545))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 2
    wall = NormalWall(pos_start=(-463, 547),
                      pos_end=(-463, 329))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 3
    wall = NormalWall(pos_start=(-459, 547),
                      pos_end=(-459, 329))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 4
    wall = NormalWall(pos_start=(-645, 291),
                      pos_end=(-501, 291))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 5
    wall = NormalWall(pos_start=(-455, 545),
                      pos_end=(-430, 545))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 6
    wall = NormalWall(pos_start=(-433, 547),
                      pos_end=(-433, 310))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 7
    wall = NormalWall(pos_start=(-673, 262),
                      pos_end=(-485, 262))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 8
    wall = NormalWall(pos_start=(-429, 547),
                      pos_end=(-429, 310))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 9
    wall = NormalWall(pos_start=(-673, 258),
                      pos_end=(-485, 258))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 10
    wall = NormalWall(pos_start=(-425, 545),
                      pos_end=(844, 545))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 11
    wall = NormalWall(pos_start=(-675, 444),
                      pos_end=(-675, 255))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 12
    wall = NormalWall(pos_start=(-674, 441),
                      pos_end=(-551, 441))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 13
    wall = NormalWall(pos_start=(-554, 443),
                      pos_end=(-554, 413))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 14
    wall = NormalWall(pos_start=(-674, 437),
                      pos_end=(-551, 437))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 15
    wall = NormalWall(pos_start=(-558, 443),
                      pos_end=(-558, 413))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 16
    wall = NormalWall(pos_start=(-671, 444),
                      pos_end=(-671, 255))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 17
    wall = NormalWall(pos_start=(-647, 418),
                      pos_end=(-647, 288))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 18
    wall = NormalWall(pos_start=(-646, 415),
                      pos_end=(-555, 415))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 19
    wall = NormalWall(pos_start=(-646, 411),
                      pos_end=(-555, 411))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 20
    wall = NormalWall(pos_start=(-643, 418),
                      pos_end=(-643, 288))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 21
    wall = NormalWall(pos_start=(-306, 402),
                      pos_end=(-306, 267))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 22
    wall = NormalWall(pos_start=(-738, 138),
                      pos_end=(-439, 138))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 23
    wall = NormalWall(pos_start=(-736, 140),
                      pos_end=(-736, -107))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 24
    wall = NormalWall(pos_start=(-305, 399),
                      pos_end=(127, 399))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 25
    wall = NormalWall(pos_start=(120, 401),
                      pos_end=(350, 8))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 26
    wall = NormalWall(pos_start=(345, 15),
                      pos_end=(345, -140))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 27
    wall = NormalWall(pos_start=(339, -134),
                      pos_end=(534, -134))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 28
    wall = NormalWall(pos_start=(531, -133),
                      pos_end=(531, -161))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 29
    wall = NormalWall(pos_start=(-305, 395),
                      pos_end=(127, 395))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 30
    wall = NormalWall(pos_start=(118, 397),
                      pos_end=(346, 7))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 31
    wall = NormalWall(pos_start=(341, 15),
                      pos_end=(341, -140))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 32
    wall = NormalWall(pos_start=(339, -138),
                      pos_end=(534, -138))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 33
    wall = NormalWall(pos_start=(527, -133),
                      pos_end=(527, -161))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 34
    wall = NormalWall(pos_start=(-302, 402),
                      pos_end=(-302, 267))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 35
    wall = NormalWall(pos_start=(-738, 134),
                      pos_end=(-439, 134))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 36
    wall = NormalWall(pos_start=(-732, 140),
                      pos_end=(-732, -107))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 37
    wall = NormalWall(pos_start=(293, 396),
                      pos_end=(431, 164))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 38
    wall = NormalWall(pos_start=(424, 168),
                      pos_end=(551, 168))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 39
    wall = NormalWall(pos_start=(549, 170),
                      pos_end=(549, 127))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 40
    wall = NormalWall(pos_start=(264, 374),
                      pos_end=(292, 394))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 41
    wall = NormalWall(pos_start=(291, 393),
                      pos_end=(429, 159))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 42
    wall = NormalWall(pos_start=(424, 164),
                      pos_end=(551, 164))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 43
    wall = NormalWall(pos_start=(545, 170),
                      pos_end=(545, 127))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 44
    wall = NormalWall(pos_start=(268, 372),
                      pos_end=(293, 390))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 45
    wall = NormalWall(pos_start=(265, 377),
                      pos_end=(413, 126))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 46
    wall = NormalWall(pos_start=(407, 130),
                      pos_end=(464, 130))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 47
    wall = NormalWall(pos_start=(458, 136),
                      pos_end=(458, -14))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 48
    wall = NormalWall(pos_start=(456, -12),
                      pos_end=(663, -12))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 49
    wall = NormalWall(pos_start=(656, -7),
                      pos_end=(656, -271))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 50
    wall = NormalWall(pos_start=(269, 377),
                      pos_end=(416, 129))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 51
    wall = NormalWall(pos_start=(407, 134),
                      pos_end=(464, 134))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 52
    wall = NormalWall(pos_start=(462, 136),
                      pos_end=(462, -14))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 53
    wall = NormalWall(pos_start=(456, -8),
                      pos_end=(663, -8))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 54
    wall = NormalWall(pos_start=(660, -7),
                      pos_end=(660, -271))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 55
    wall = NormalWall(pos_start=(-265, 366),
                      pos_end=(-265, 246))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 56
    wall = NormalWall(pos_start=(-382, 136),
                      pos_end=(-382, -109))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 57
    wall = NormalWall(pos_start=(-264, 363),
                      pos_end=(98, 363))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 58
    wall = NormalWall(pos_start=(91, 365),
                      pos_end=(307, -4))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 59
    wall = NormalWall(pos_start=(302, 2),
                      pos_end=(302, -293))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 60
    wall = NormalWall(pos_start=(-264, 359),
                      pos_end=(98, 359))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 61
    wall = NormalWall(pos_start=(88, 361),
                      pos_end=(303, -5))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 62
    wall = NormalWall(pos_start=(298, 2),
                      pos_end=(298, -293))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 63
    wall = NormalWall(pos_start=(-261, 366),
                      pos_end=(-261, 246))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 64
    wall = NormalWall(pos_start=(-378, 136),
                      pos_end=(-378, -109))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 65
    wall = NormalWall(pos_start=(-645, 295),
                      pos_end=(-501, 295))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 66
    wall = NormalWall(pos_start=(-508, 290),
                      pos_end=(-459, 339))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 67
    wall = NormalWall(pos_start=(-507, 286),
                      pos_end=(-457, 337))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 68
    wall = NormalWall(pos_start=(-492, 257),
                      pos_end=(-431, 319))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 69
    wall = NormalWall(pos_start=(-491, 253),
                      pos_end=(-427, 318))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 70
    wall = NormalWall(pos_start=(-446, 133),
                      pos_end=(-304, 276))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 71
    wall = NormalWall(pos_start=(-445, 129),
                      pos_end=(-300, 275))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 72
    wall = NormalWall(pos_start=(-387, 130),
                      pos_end=(-263, 255))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 73
    wall = NormalWall(pos_start=(-383, 129),
                      pos_end=(-259, 254))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 74
    wall = NormalWall(pos_start=(660, 171),
                      pos_end=(660, 127))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 75
    wall = NormalWall(pos_start=(661, 168),
                      pos_end=(846, 168))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 76
    wall = NormalWall(pos_start=(661, 164),
                      pos_end=(846, 164))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 77
    wall = NormalWall(pos_start=(664, 171),
                      pos_end=(664, 127))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 78
    wall = NormalWall(pos_start=(658, 134),
                      pos_end=(846, 134))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 79
    wall = NormalWall(pos_start=(492, 137),
                      pos_end=(492, 20))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 80
    wall = NormalWall(pos_start=(493, 134),
                      pos_end=(548, 134))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 81
    wall = NormalWall(pos_start=(493, 130),
                      pos_end=(548, 130))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 82
    wall = NormalWall(pos_start=(496, 137),
                      pos_end=(496, 20))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 83
    wall = NormalWall(pos_start=(658, 130),
                      pos_end=(846, 130))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 84
    wall = NormalWall(pos_start=(-178, 64),
                      pos_end=(-178, -34))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 85
    wall = NormalWall(pos_start=(-115, 124),
                      pos_end=(-21, 124))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 86
    wall = NormalWall(pos_start=(38, 61),
                      pos_end=(38, -38))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 87
    wall = NormalWall(pos_start=(-181, 57),
                      pos_end=(-111, 128))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 88
    wall = NormalWall(pos_start=(-29, 126),
                      pos_end=(43, 55))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 89
    wall = NormalWall(pos_start=(-168, 61),
                      pos_end=(-168, -31))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 90
    wall = NormalWall(pos_start=(-110, 115),
                      pos_end=(-26, 115))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 91
    wall = NormalWall(pos_start=(28, 58),
                      pos_end=(28, -35))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 92
    wall = NormalWall(pos_start=(-171, 54),
                      pos_end=(-105, 121))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 93
    wall = NormalWall(pos_start=(-33, 117),
                      pos_end=(33, 52))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 94
    wall = NormalWall(pos_start=(-710, 111),
                      pos_end=(-710, -107))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 95
    wall = NormalWall(pos_start=(-734, -100),
                      pos_end=(-705, -100))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 96
    wall = NormalWall(pos_start=(-709, 108),
                      pos_end=(-532, 108))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 97
    wall = NormalWall(pos_start=(-535, 110),
                      pos_end=(-535, -106))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 98
    wall = NormalWall(pos_start=(-540, -99),
                      pos_end=(-512, -99))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 99
    wall = NormalWall(pos_start=(-514, 110),
                      pos_end=(-514, -106))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 100
    wall = NormalWall(pos_start=(-513, 107),
                      pos_end=(-409, 107))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 101
    wall = NormalWall(pos_start=(-412, 109),
                      pos_end=(-412, -118))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 102
    wall = NormalWall(pos_start=(-709, 104),
                      pos_end=(-532, 104))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 103
    wall = NormalWall(pos_start=(-539, 110),
                      pos_end=(-539, -106))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 104
    wall = NormalWall(pos_start=(-540, -103),
                      pos_end=(-512, -103))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 105
    wall = NormalWall(pos_start=(-706, 111),
                      pos_end=(-706, -107))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 106
    wall = NormalWall(pos_start=(-734, -104),
                      pos_end=(-705, -104))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 107
    wall = NormalWall(pos_start=(-513, 103),
                      pos_end=(-409, 103))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 108
    wall = NormalWall(pos_start=(-416, 109),
                      pos_end=(-416, -118))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 109
    wall = NormalWall(pos_start=(-510, 110),
                      pos_end=(-510, -106))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 110
    wall = NormalWall(pos_start=(490, 27),
                      pos_end=(709, 27))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 111
    wall = NormalWall(pos_start=(706, 28),
                      pos_end=(706, -273))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 112
    wall = NormalWall(pos_start=(701, -266),
                      pos_end=(845, -266))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 113
    wall = NormalWall(pos_start=(490, 23),
                      pos_end=(709, 23))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 114
    wall = NormalWall(pos_start=(702, 28),
                      pos_end=(702, -273))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 115
    wall = NormalWall(pos_start=(701, -270),
                      pos_end=(845, -270))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 116
    wall = NormalWall(pos_start=(-170, -24),
                      pos_end=(-105, -89))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 117
    wall = NormalWall(pos_start=(-111, -84),
                      pos_end=(-22, -84))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 118
    wall = NormalWall(pos_start=(-29, -87),
                      pos_end=(30, -27))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 119
    wall = NormalWall(pos_start=(-119, -94),
                      pos_end=(-23, -94))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 120
    wall = NormalWall(pos_start=(-29, -99),
                      pos_end=(41, -29))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 121
    wall = NormalWall(pos_start=(-180, -27),
                      pos_end=(-111, -96))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 122
    wall = NormalWall(pos_start=(-380, -100),
                      pos_end=(-348, -133))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 123
    wall = NormalWall(pos_start=(-384, -101),
                      pos_end=(-353, -133))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 124
    wall = NormalWall(pos_start=(-415, -109),
                      pos_end=(-374, -150))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 125
    wall = NormalWall(pos_start=(-419, -110),
                      pos_end=(-374, -154))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 126
    wall = NormalWall(pos_start=(-378, -156),
                      pos_end=(-349, -127))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 127
    wall = NormalWall(pos_start=(-378, -151),
                      pos_end=(-355, -127))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 128
    wall = NormalWall(pos_start=(341, -156),
                      pos_end=(341, -316))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 129
    wall = NormalWall(pos_start=(236, -373),
                      pos_end=(342, -308))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 130
    wall = NormalWall(pos_start=(342, -159),
                      pos_end=(530, -159))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 131
    wall = NormalWall(pos_start=(342, -163),
                      pos_end=(530, -163))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 132
    wall = NormalWall(pos_start=(345, -156),
                      pos_end=(345, -316))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 133
    wall = NormalWall(pos_start=(235, -378),
                      pos_end=(347, -310))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 134
    wall = NormalWall(pos_start=(-229, -290),
                      pos_end=(12, -290))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 135
    wall = NormalWall(pos_start=(2, -288),
                      pos_end=(70, -399))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 136
    wall = NormalWall(pos_start=(-213, -259),
                      pos_end=(36, -259))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 137
    wall = NormalWall(pos_start=(29, -257),
                      pos_end=(117, -404))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 138
    wall = NormalWall(pos_start=(111, -404),
                      pos_end=(140, -385))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 139
    wall = NormalWall(pos_start=(134, -387),
                      pos_end=(159, -425))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 140
    wall = NormalWall(pos_start=(-312, -213),
                      pos_end=(-283, -183))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 141
    wall = NormalWall(pos_start=(-288, -182),
                      pos_end=(-206, -265))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 142
    wall = NormalWall(pos_start=(-731, -188),
                      pos_end=(-731, -445))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 143
    wall = NormalWall(pos_start=(-733, -192),
                      pos_end=(-690, -192))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 144
    wall = NormalWall(pos_start=(-693, -190),
                      pos_end=(-693, -417))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 145
    wall = NormalWall(pos_start=(-698, -410),
                      pos_end=(-653, -410))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 146
    wall = NormalWall(pos_start=(-656, -409),
                      pos_end=(-656, -445))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 147
    wall = NormalWall(pos_start=(-229, -286),
                      pos_end=(12, -286))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 148
    wall = NormalWall(pos_start=(5, -284),
                      pos_end=(77, -404))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 149
    wall = NormalWall(pos_start=(-213, -263),
                      pos_end=(36, -263))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 150
    wall = NormalWall(pos_start=(27, -261),
                      pos_end=(116, -410))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 151
    wall = NormalWall(pos_start=(110, -409),
                      pos_end=(138, -391))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 152
    wall = NormalWall(pos_start=(132, -393),
                      pos_end=(154, -425))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 153
    wall = NormalWall(pos_start=(-307, -213),
                      pos_end=(-282, -188))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 154
    wall = NormalWall(pos_start=(-289, -187),
                      pos_end=(-207, -268))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 155
    wall = NormalWall(pos_start=(-733, -196),
                      pos_end=(-690, -196))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 156
    wall = NormalWall(pos_start=(-697, -190),
                      pos_end=(-697, -417))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 157
    wall = NormalWall(pos_start=(-698, -414),
                      pos_end=(-653, -414))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 158
    wall = NormalWall(pos_start=(-660, -409),
                      pos_end=(-660, -445))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 159
    wall = NormalWall(pos_start=(-727, -188),
                      pos_end=(-727, -445))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 160
    wall = NormalWall(pos_start=(-536, -195),
                      pos_end=(-536, -416))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 161
    wall = NormalWall(pos_start=(-574, -409),
                      pos_end=(-531, -409))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 162
    wall = NormalWall(pos_start=(-572, -407),
                      pos_end=(-572, -444))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 163
    wall = NormalWall(pos_start=(-535, -198),
                      pos_end=(-499, -198))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 164
    wall = NormalWall(pos_start=(-502, -196),
                      pos_end=(-502, -407))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 165
    wall = NormalWall(pos_start=(-507, -400),
                      pos_end=(-403, -400))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 166
    wall = NormalWall(pos_start=(-535, -202),
                      pos_end=(-499, -202))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 167
    wall = NormalWall(pos_start=(-506, -196),
                      pos_end=(-506, -407))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 168
    wall = NormalWall(pos_start=(-507, -404),
                      pos_end=(-403, -404))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 169
    wall = NormalWall(pos_start=(-532, -195),
                      pos_end=(-532, -416))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 170
    wall = NormalWall(pos_start=(-574, -413),
                      pos_end=(-531, -413))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 171
    wall = NormalWall(pos_start=(-568, -407),
                      pos_end=(-568, -444))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 172
    wall = NormalWall(pos_start=(-311, -207),
                      pos_end=(-223, -295))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 173
    wall = NormalWall(pos_start=(-305, -207),
                      pos_end=(-222, -291))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 174
    wall = NormalWall(pos_start=(459, -261),
                      pos_end=(459, -308))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 175
    wall = NormalWall(pos_start=(460, -264),
                      pos_end=(659, -264))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 176
    wall = NormalWall(pos_start=(460, -268),
                      pos_end=(659, -268))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 177
    wall = NormalWall(pos_start=(463, -261),
                      pos_end=(463, -308))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 178
    wall = NormalWall(pos_start=(211, -338),
                      pos_end=(297, -285))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 179
    wall = NormalWall(pos_start=(-405, -308),
                      pos_end=(-405, -407))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 180
    wall = NormalWall(pos_start=(-274, -399),
                      pos_end=(75, -399))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 181
    wall = NormalWall(pos_start=(217, -339),
                      pos_end=(304, -285))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 182
    wall = NormalWall(pos_start=(-410, -314),
                      pos_end=(-382, -285))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 183
    wall = NormalWall(pos_start=(-387, -284),
                      pos_end=(-267, -404))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 184
    wall = NormalWall(pos_start=(-401, -308),
                      pos_end=(-401, -407))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 185
    wall = NormalWall(pos_start=(-274, -403),
                      pos_end=(75, -403))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 186
    wall = NormalWall(pos_start=(-406, -315),
                      pos_end=(-381, -290))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 187
    wall = NormalWall(pos_start=(-388, -289),
                      pos_end=(-268, -408))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 188
    wall = NormalWall(pos_start=(457, -301),
                      pos_end=(846, -301))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 189
    wall = NormalWall(pos_start=(457, -305),
                      pos_end=(846, -305))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 190
    wall = NormalWall(pos_start=(843, 547),
                      pos_end=(843, -544))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 191
    wall = NormalWall(pos_start=(212, -334),
                      pos_end=(241, -376))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 192
    wall = NormalWall(pos_start=(217, -335),
                      pos_end=(242, -371))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 193
    wall = NormalWall(pos_start=(330, -432),
                      pos_end=(406, -385))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 194
    wall = NormalWall(pos_start=(399, -389),
                      pos_end=(745, -389))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 195
    wall = NormalWall(pos_start=(742, -387),
                      pos_end=(742, -415))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 196
    wall = NormalWall(pos_start=(399, -393),
                      pos_end=(745, -393))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 197
    wall = NormalWall(pos_start=(738, -387),
                      pos_end=(738, -415))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 198
    wall = NormalWall(pos_start=(333, -435),
                      pos_end=(398, -394))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 199
    wall = NormalWall(pos_start=(472, -410),
                      pos_end=(472, -546))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 200
    wall = NormalWall(pos_start=(473, -413),
                      pos_end=(741, -413))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 201
    wall = NormalWall(pos_start=(473, -417),
                      pos_end=(741, -417))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 202
    wall = NormalWall(pos_start=(476, -410),
                      pos_end=(476, -546))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 203
    wall = NormalWall(pos_start=(347, -458),
                      pos_end=(415, -415))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 204
    wall = NormalWall(pos_start=(407, -420),
                      pos_end=(444, -420))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 205
    wall = NormalWall(pos_start=(441, -418),
                      pos_end=(441, -546))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 206
    wall = NormalWall(pos_start=(118, -446),
                      pos_end=(157, -420))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 207
    wall = NormalWall(pos_start=(-574, -441),
                      pos_end=(124, -441))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 208
    wall = NormalWall(pos_start=(407, -424),
                      pos_end=(444, -424))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 209
    wall = NormalWall(pos_start=(437, -418),
                      pos_end=(437, -546))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 210
    wall = NormalWall(pos_start=(117, -442),
                      pos_end=(146, -422))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 211
    wall = NormalWall(pos_start=(-574, -437),
                      pos_end=(124, -437))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 212
    wall = NormalWall(pos_start=(346, -463),
                      pos_end=(408, -424))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 213
    wall = NormalWall(pos_start=(335, -430),
                      pos_end=(354, -456))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 214
    wall = NormalWall(pos_start=(331, -431),
                      pos_end=(352, -461))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 215
    wall = NormalWall(pos_start=(-733, -438),
                      pos_end=(-654, -438))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 216
    wall = NormalWall(pos_start=(-733, -442),
                      pos_end=(-654, -442))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 217
    wall = NormalWall(pos_start=(-846, -543),
                      pos_end=(845, -543))
    playground.add(wall, wall.wall_coordinates)

