FRAME_RATE = 1/30
LINEAR_SPEED_RATIO = 3.0
ANGULAR_SPEED_RATIO = 0.6

DRONE_INITIAL_HEALTH = 50

RESOLUTION_SEMANTIC_SENSOR = 35
MAX_RANGE_SEMANTIC_SENSOR = 200
FOV_SEMANTIC_SENSOR = 360

RESOLUTION_LIDAR_SENSOR = 181
MAX_RANGE_LIDAR_SENSOR = 300
FOV_LIDAR_SENSOR = 360

# 'RANGE_COMMUNICATION' is the radius, in pixels, of the area around the drone in which we will have the other
# drones with which we can communicate (receive and send messages)
RANGE_COMMUNICATION = 250
