"""
This file was generated by the tool 'map_editor_gui.py' in the directory map_editor.
This tool permits to create this kind of file by using a graphical interface.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox

# Dimension of the map : (706, 706)

def dimensions():
    return (706,706)

def add_walls(playground):

    pass


def add_boxes(playground):

    pass

