"""
This file was generated by the tool 'map_editor_gui.py' in the directory map_editor.
This tool permits to create this kind of file by using a graphical interface.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox

# Dimension of the map : (802, 602)

def dimensions(playground):

    return(802,602)

def add_walls(playground):

    wall = NormalWall(pos_start=(0, 1), pos_end=(802, 1))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(801, 0), pos_end=(801, 602))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(802, 601), pos_end=(0, 601))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(1, 602), pos_end=(1, 0))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(353, 359), pos_end=(-23, 359))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(312, 510), pos_end=(964, 510))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(679, 125), pos_end=(679, -36))
    playground.add(wall, wall.wall_coordinates)


def add_boxes(playground):

    box = NormalBox(up_left_point=(300, 98), width=60, height=39)
    playground.add(box, box.wall_coordinates)

    box = NormalBox(up_left_point=(537, 215), width=39, height=174)
    playground.add(box, box.wall_coordinates)

