"""
This file was generated by the tool 'map_editor_gui.py' in the directory map_editor.
This tool permits to create this kind of file by using a graphical interface.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox

# Dimension of the map : (802, 602)

def dimensions():
    return (802,602)

def add_walls(playground):

    wall = NormalWall(pos_start=(-401, 300), pos_end=(401, 300))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-401, -300), pos_end=(401, -300))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-400, 301), pos_end=(-400, -301))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-456, 63), pos_end=(-169, 63))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-169, 64), pos_end=(-169, -184))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-401, 300), pos_end=(401, 300))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(400, 301), pos_end=(400, -301))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-401, -300), pos_end=(401, -300))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-400, 301), pos_end=(-400, -301))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(115, 31), pos_end=(404, 31))
    playground.add(wall, wall.wall_coordinates)


def add_boxes(playground):

    box = NormalBox(up_left_point=(-334, 256), width=168, height=105)
    playground.add(box, box.wall_coordinates)

